---

- name: Install HBase
  hosts: hbase
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Create bigdata home directory
      become: yes
      file:
        dest: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/{{ installer.hbase }}"
        dest: "{{ bigdata_home }}/{{ installer.hbase }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.hbase }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.hbase }}"
        state: absent
    - name: Create hbase symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.hbase.replace('-bin.tar.gz', '') }}"
        dest: "{{ hbase_home }}"
        state: link

    - name: Add hbase configuration
      template:
        src: "hbase/{{ item }}"
        dest: "{{ hbase_home }}/conf/"
        mode: 0644
      with_items:
          - "regionservers"
