---

# 다 안돼서 docker로 함
# docker repository kdev01에 구성 후 docker 설치
# docker image 'hue-4.10.0' load
# docker compose 실행

- name: Install Hue in Docker
  hosts: hue
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    - hue_home: "{{ bigdata_home }}/hue"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Create Hue home directory
      file:
        path: "{{ bigdata_home }}/hue-4.10.0"
        state: directory
    - name: Create Hue home symbolic link
      file:
        src: "{{ bigdata_home }}/hue-4.10.0"
        dest: "{{ hue_home }}"
        state: link
    - name: Create Hue bin directory
      file:
        path: "{{ hue_home }}/bin"
        state: directory
    - name: Create Hue conf directory
      file:
        path: "{{ hue_home }}/conf"
        state: directory
    - name: Create Hue logs directory
      file:
        path: "{{ hue_home }}/logs"
        state: directory
    - name: Add configuration files
      template:
        src: hue/{{ item.key }}
        dest: "{{ item.value }}"
      with_dict:
        "docker-compose.yml": "{{ hue_home }}"
        "db-init.sh": "{{ hue_home }}/bin"
        "hue.ini": "{{ hue_home }}/conf"
    - name: Create yum docker repository
      copy:
        -



