---

- name: Install Airflow
  hosts: airflow-webserver, airflow-scheduler, airflow-celery-worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Create temporary directory
      file:
        dest: "/home/{{ remote_user }}/airflow-tmp"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/airflow/{{ item }}"
        dest: "/home/{{ remote_user }}/airflow-tmp/"
      with_items:
        - "airflow-download.tgz"
    - name: Unzip whls
      unarchive:
        src: "/home/{{ remote_user }}/airflow-tmp/airflow-download.tgz"
        dest: "/home/{{ remote_user }}/airflow-tmp/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Install Airflow
      pip:
        name: "apache-airflow[celery]==2.5.1"
        extra_args: "--no-index -f /home/{{ remote_user }}/airflow-tmp/airflow-download/airflow_whls"
        state: present
    - name: Remove temporary directory
      file:
        dest: "/home/{{ remote_user }}/airflow-tmp"
        state: absent
    - name: Edit Airflow home directory
      lineinfile:
        path: "/home/{{ remote_user }}/.bashrc"
        regexp: "^#? *{{ item.key | regex_escape() }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        "export AIRFLOW_HOME": "\"{{ airflow_home }}\""
    - name: Setup Airflow home directory
      command: "~/.pyenv/shims/airflow"
    - name: Edit Airflow configuration
      lineinfile:
        path: "/home/{{ remote_user }}/.bashrc"
        regexp: "^{{ item.key | regex_escape() }} ="
        line: "{{ item.key }} = {{ item.value }}"
      with_dict:
        "default_timezone": "Asia/Seoul"
        "executor": "CeleryExecutor"
        "load_examples": "False"
        "sql_alchemy_conn": "mysql://{{ airflow.db_user }}:{{ airflow.db_pw }}@{{ groups['mysql'] }}:{{ mysql.jdbc_port }}/{{ airflow.db_name }}"
        "celery_logging_level": "INFO"
        "default_ui_timezone": "Asia/Seoul"
        "web_server_port": "{{ airflow.web_port }}"
        "broker_url": "{% for r in groups['redis'] %}{% if r != groups['redis'][0] %};{% endif %}sentinel://{{ r }}:{{ redis.sentinel_port }}{% endfor %}"
        "# result_backend": "mysql://{{ airflow.db_user }}:{{ airflow.db_pw }}@{{ groups['mysql'] }}:{{ mysql.jdbc_port }}/{{ airflow.db_name }}"
        "dag_dir_list_interval": "{{ airflow.dag_dir_list_interval }}"

## Meta Database
- name: Setting up a MySQL Database
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Create DB, User
      shell: |
        bin/mysql -uroot -p{{ mysql.root_pw }} --socket={{ mysql.socket_dir }}/mysql.sock -e "CREATE DATABASE {{ airflow.db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        bin/mysql -uroot -p{{ mysql.root_pw }} --socket={{ mysql.socket_dir }}/mysql.sock -e "CREATE USER '{{ airflow.db_user }}'@'localhost' IDENTIFIED BY '{{ airflow.db_pw }}';"
        bin/mysql -uroot -p{{ mysql.root_pw }} --socket={{ mysql.socket_dir }}/mysql.sock -e "GRANT ALL PRIVILEGES ON {{ airflow.db_name }}.* TO '{{ airflow.db_user }}'@'localhost';"
      args:
        chdir: "{{ mysql.home_dir }}"

- name: Setting up a MySQL Database
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Create DB, User
      shell: |
        bin/mysql -uroot -p{{ mysql.root_pw }} --socket={{ mysql.socket_dir }}/mysql.sock -e "CREATE USER '{{ airflow.db_user }}'@'{{ item }}' IDENTIFIED BY '{{ airflow.db_pw }}';"
        bin/mysql -uroot -p{{ mysql.root_pw }} --socket={{ mysql.socket_dir }}/mysql.sock -e "GRANT ALL PRIVILEGES ON {{ airflow.db_name }}.* TO '{{ airflow.db_user }}'@'{{ item }}';"
      args:
        chdir: "{{ mysql.home_dir }}"
      with_items: "{{ groups['airflow'] }}"

## Scheduler H/A


## Start Webserver, Scheduler

