---

- name: Install CheckProcessExporter
  hosts: check-process-exporter
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    check_process_exporter_home: "{{ bigdata_home }}/check_process_exporter"
    pyenv_home: "/home/{{ remote_user }}/.pyenv"
  tasks:
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/prometheus/{{ installer.check_process_exporter }}"
        dest: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ check_process_exporter_home }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
        state: absent
    - name: Create Prometheus symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.check_process_exporter.replace('.zip', '') }}"
        dest: "{{ check_process_exporter_home }}"
        state: link
    - name: Create log directory
      file:
        path: "{{ check_process_exporter_home }}/{{ item }}"
        state: directory
      with_items:
        - "logs"
    - name: Check CheckProcessExporter Process
      shell: "/usr/bin/ps -ef | grep -v grep | grep check_process_exporter.py"
      register: cpe_ps
      failed_when: false
    - name: Start CheckProcessExporter
      shell: "/usr/bin/nohup {{ pyenv_home }}/shims/python {{ check_process_exporter_home }}/check_process_exporter.py > {{ check_process_exporter_home }}/logs/cp_exporter.log 2>&1 &"
      when: '"check_process_exporter" not in cpe_ps.stdout'
