---

- name: Install MySQL
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    mysql_home_parent: "{{ mysql.home_dir.replace('/mysql','') }}"
  tasks:
    - name: Create home directory
      file:
        path: "{{ mysql_home_parent }}"
        state: directory
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/mysql/{{ installer.mysql }}"
        dest: "{{ mysql_home_parent }}/{{ installer.mysql }}"
    - name: Unzip installer
      unarchive:
        src: "{{ mysql_home_parent }}/{{ installer.mysql }}"
        dest: "{{ mysql_home_parent }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete installer
      file:
        path: "{{ mysql_home_parent }}/{{ installer.mysql }}"
        state: absent
    - name: Create MySQL symbolic link
      file:
        src: "{{ mysql_home_parent }}/{{ installer.mysql.replace('.tar.xz', '') }}"
        dest: "{{ mysql.home_dir }}"
        state: link
    - name: Create configuration and log directory
      file:
        path: "{{ mysql.home_dir }}/{{ item }}"
        state: directory
      with_items:
        - conf
        - logs
    - name: Create configuration file
      template:
        src: mysql/my.cnf
        dest: "{{ mysql.home_dir }}/conf/"
        mode: 0644
    - name: Create data directory
      become: yes
      file:
        path: "{{ mysql.data_dir }}"
        state: directory
        owner: "{{ remote_user }}"
    - name: Install OS Library
      become: yes
      yum:
        name:
          - "libaio"
          - "numactl"
    - name: Install MySQL
      command: "{{ mysql.home_dir }}/bin/mysqld --defaults-file={{ mysql.home_dir }}/conf/my.cnf --initialize-insecure --user={{ remote_user }}"
    - name: Start MySQL
      shell: "/usr/bin/nohup {{ mysql.home_dir }}/bin/mysqld_safe --defaults-file={{ mysql.home_dir }}/conf/my.cnf --user={{ remote_user }} &"
    - name: Secure installation
      expect:
        command: "{{ mysql.home_dir }}/bin/mysql_secure_installation --defaults-file={{ mysql.home_dir }}/conf/my.cnf"
        responses:
          'Press y|Y for Yes, any other key for No:': 'n'
          'New password:': "{{ mysql.root_pw }}"
          'Re-enter new password:': "{{ mysql.root_pw }}"
          'Remove anonymous users\? \(Press y|Y for Yes, any other key for No\) :': 'y'
          'Disallow root login remotely\? \(Press y|Y for Yes, any other key for No\) :': 'y'
          'Remove test database and access to it\? \(Press y|Y for Yes, any other key for No\) :': 'y'
          'Reload privilege tables now\? \(Press y|Y for Yes, any other key for No\) :': 'y'
    - name: Test MySQL
      command: "{{ mysql.home_dir }}/bin/mysql -u root -p {{ mysql.root_pw }} --socket={{ mariadb.socket_dir }}/mysql.sock -e 'SHOW DATABASES;'"
