---

## Ranger Plugin - HDFS 설치
- name: Install Ranger Plugins - HDFS
  hosts: namenode
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hdfs_plugin_home: "{{ plugin_home }}/hdfs"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
      with_items:
        - "{{ bigdata_home }}"
        - "{{ plugin_home }}"
    - name: Copy HDFS Plugin installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.ranger_hdfs }}"
        dest: "{{ plugin_home }}/{{ installer.ranger_hdfs }}"
    - name: Unzip HDFS Plugin installer
      unarchive:
        src: "{{ plugin_home }}/{{ installer.ranger_hdfs }}"
        dest: "{{ plugin_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ plugin_home }}/{{ installer.ranger_hdfs.replace('.tar.gz', '') }}"
    - name: Delete HDFS Plugin installer
      file:
        path: "{{ plugin_home }}/{{ installer.ranger_hdfs }}"
        state: absent
    - name: Create HDFS Plugin symbolic link
      file:
        src: "{{ plugin_home }}/{{ installer.ranger_hdfs.replace('.tar.gz', '') }}"
        dest: "{{ hdfs_plugin_home }}"
        state: link
    - name: Add install properties
      template:
        src: "ranger/plugin/hdfs/{{ item }}"
        dest: "{{ hdfs_plugin_home }}/"
        mode: 0644
      with_items:
        - "install.properties"
    - name: Enable Ranger HDFS Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hdfs_plugin_home }}/enable-hdfs-plugin.sh"

## Ranger Plugin - YARN 설치
- name: Install Ranger Plugins - YARN
  hosts: resourcemanager
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hadoop_home: "{{ bigdata_home }}/hadoop"
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    yarn_plugin_home: "{{ plugin_home }}/yarn"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
      with_items:
        - "{{ bigdata_home }}"
        - "{{ plugin_home }}"
    - name: Copy YARN Plugin installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.ranger_yarn }}"
        dest: "{{ plugin_home }}/{{ installer.ranger_yarn }}"
    - name: Unzip YARN Plugin installer
      unarchive:
        src: "{{ plugin_home }}/{{ installer.ranger_yarn }}"
        dest: "{{ plugin_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ plugin_home }}/{{ installer.ranger_yarn.replace('.tar.gz', '') }}"
    - name: Delete YARN Plugin installer
      file:
        path: "{{ plugin_home }}/{{ installer.ranger_yarn }}"
        state: absent
    - name: Create YARN Plugin symbolic link
      file:
        src: "{{ plugin_home }}/{{ installer.ranger_yarn.replace('.tar.gz', '') }}"
        dest: "{{ yarn_plugin_home }}"
        state: link
    - name: Add install properties
      template:
        src: "ranger/plugin/yarn/{{ item }}"
        dest: "{{ yarn_plugin_home }}/"
        mode: 0644
      with_items:
        - "install.properties"
    - name: Create library symbolic link
      file:
        src: "{{ hadoop_home }}/share/hadoop/hdfs/lib/{{ item }}"
        dest: "{{ yarn_plugin_home }}/install/lib/{{ item }}"
        state: link
      with_items:
        - "commons-logging-1.1.3.jar"
        - "commons-lang3-3.7.jar"
        - "htrace-core4-4.1.0-incubating.jar"
        - "commons-compress-1.21.jar"
    - name: Enable Ranger YARN Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ yarn_plugin_home }}/enable-yarn-plugin.sh"

## Ranger Plugin - Hive 설치
- name: Install Ranger Plugins - Hive
  hosts: hive-server2
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hive_home: "{{ bigdata_home }}/hive"
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hive_plugin_home: "{{ plugin_home }}/hive"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
      with_items:
        - "{{ bigdata_home }}"
        - "{{ plugin_home }}"
    - name: Copy Hive Plugin installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.ranger_hive }}"
        dest: "{{ plugin_home }}/{{ installer.ranger_hive }}"
    - name: Unzip Hive Plugin installer
      unarchive:
        src: "{{ plugin_home }}/{{ installer.ranger_hive }}"
        dest: "{{ plugin_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ plugin_home }}/{{ installer.ranger_hive.replace('.tar.gz', '') }}"
    - name: Delete Hive Plugin installer
      file:
        path: "{{ plugin_home }}/{{ installer.ranger_hive }}"
        state: absent
    - name: Create Hive Plugin symbolic link
      file:
        src: "{{ plugin_home }}/{{ installer.ranger_hive.replace('.tar.gz', '') }}"
        dest: "{{ hive_plugin_home }}"
        state: link
    - name: Add install properties
      template:
        src: "ranger/plugin/hive/{{ item }}"
        dest: "{{ hive_plugin_home }}/"
        mode: 0644
      with_items:
        - "install.properties"
    - name: Modify disable configuration file
      template:
        src: "ranger/plugin/hive/{{ item }}"
        dest: "{{ hive_plugin_home }}/install/conf.templates/disable/"
        mode: 0700
      with_items:
        - "hiveserver2-site-changes.cfg"
    - name: Enable Ranger Hive Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hive_plugin_home }}/enable-hive-plugin.sh"

## Ranger Plugin - HBase 설치
- name: Install Ranger Plugins - HBase
  hosts: hbase, worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hbase_plugin_home: "{{ plugin_home }}/hbase"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ item }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
      with_items:
        - "{{ bigdata_home }}"
        - "{{ plugin_home }}"
    - name: Copy HBase Plugin installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.ranger_hbase }}"
        dest: "{{ plugin_home }}/{{ installer.ranger_hbase }}"
    - name: Unzip HBase Plugin installer
      unarchive:
        src: "{{ plugin_home }}/{{ installer.ranger_hbase }}"
        dest: "{{ plugin_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ plugin_home }}/{{ installer.ranger_hbase.replace('.tar.gz', '') }}"
    - name: Delete HBase Plugin installer
      file:
        path: "{{ plugin_home }}/{{ installer.ranger_hbase }}"
        state: absent
    - name: Create HBase Plugin symbolic link
      file:
        src: "{{ plugin_home }}/{{ installer.ranger_hbase.replace('.tar.gz', '') }}"
        dest: "{{ hbase_plugin_home }}"
        state: link
    - name: Add install properties
      template:
        src: "ranger/plugin/hbase/{{ item }}"
        dest: "{{ hbase_plugin_home }}/"
        mode: 0644
      with_items:
        - "install.properties"
    - name: Create library symbolic link
      file:
        src: "{{ hbase_plugin_home }}/install/lib/{{ item }}"
        dest: "{{ hbase_home }}/lib/{{ item }}"
        state: link
      with_items:
        - "commons-lang-2.6.jar"
    - name: Move library
      command: "mv {{ hbase_plugin_home }}/lib/ranger-hbase-plugin-impl/jersey-core-1.19.3.jar {{ hbase_plugin_home }}/jersey-core-1.19.3.jar"
      args:
        removes: "{{ hbase_plugin_home }}/lib/ranger-hbase-plugin-impl/jersey-core-1.19.3.jar"
        creates: "{{ hbase_plugin_home }}/jersey-core-1.19.3.jar"
    - name: Enable Ranger HBase Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hbase_plugin_home }}/enable-hbase-plugin.sh"
