---

- name: Install Hive
  hosts: hive
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hive_home: "{{ bigdata_home }}/hive"
  tasks:
  - name: Create bigdata home directory
    become: yes
    file:
      dest: "{{ bigdata_home }}"
      state: directory
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
  - name: Copy installer
    copy:
      src: "{{ installer_home }}/{{ installer.hive }}"
      dest: "{{ bigdata_home }}/{{ installer.hive }}"
  - name: Unzip installer
    unarchive:
      src: "{{ bigdata_home }}/{{ installer.hive }}"
      dest: "{{ bigdata_home }}/"
      remote_src: true
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
  - name: Delete installer
    file:
      path: "{{ bigdata_home }}/{{ installer.hive }}"
      state: absent
  - name: Create MariaDB symbolic link
    file:
      src: "{{ bigdata_home }}/{{ installer.hive.replace('.tar.gz', '') }}"
      dest: "{{ hive_home }}"
      state: link

- name: Create hive metastore database
  hosts: mariadb
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hive_home: "{{ bigdata_home }}/hive"
  tasks:
  - name: Create Hive metastore databases
    command: "{{ mariadb.home_dir }}/bin/mysql --socket={{ mariadb.socket_dir }}/mysql.sock -e 'CREATE DATABASE metastore; USE metastore; SOURCE hive-schema-2.3.0.mysql.sql'"
    args:
      chdir: "{{ hive_home }}/scripts/metastore/upgrade/mysql"




