---

- name: Install Ranger
  hosts: ranger
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    solr_home: "{{ bigdata_home }}/solr"
    ranger_home: "{{ bigdata_home }}/ranger"
  tasks:
    - name: Create Create bigdata home directory
      become: yes
      file:
        dest: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"

    ## JDK 11 install (Solr 9.0부터 jdk 11 필요)
    - name: Copy JDK11 Installer
      copy:
        src: "{{ installer_home }}/jdk/{{ installer.jdk11 }}"
        dest: "{{ bigdata_home }}/{{ installer.jdk11 }}"
    - name: Unzip JDK11 installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.jdk11 }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete JDK11 installer
      file:
        path: "{{ bigdata_home }}/{{ installer.jdk11 }}"
        state: absent

    ## Solr install (Ranger audit)
    - name: Copy Solr installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.solr }}"
        dest: "{{ bigdata_home }}/{{ installer.solr }}"
    - name: Unzip Solr installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.solr }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete Solr installer
      file:
        path: "{{ bigdata_home }}/{{ installer.solr }}"
        state: absent
    - name: Create Solr symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.solr.replace('.tgz', '') }}"
        dest: "{{ solr_home }}"
        state: link
#    - name: Edit Solr configuration
#      lineinfile:
#        path: "{{ solr_home }}/bin/solr.in.sh"
#        regexp: "^#? *{{ item.key }}="
#        line: "{{ item.key }}=\"{{ item.value }}\""
#      with_dict:
#        "SOLR_JAVA_HOME": "{{ bigdata_home }}/jdk-11"
#        "ZK_HOST": "{% for zoo in groups['zookeeper'] %}{% if zoo != groups['zookeeper'][0] %},{% endif %}{{ zoo }}:{{ zookeeper.client_port }}{% endfor %}"
#        "SOLR_HEAP": "{{ solr.heapsize }}"
#        "SOLR_TIMEZONE": "Asia/Seoul"
#        "SOLR_DATA_HOME": "{{ solr.data_dir }}"
#        "SOLR_IP_ALLOWLIST": "127.0.0.1, 192.168.251.186"

    ## Ranger install
    - name: Copy Ranger installer
      copy:
        src: "{{ installer_home }}/ranger/{{ installer.ranger }}"
        dest: "{{ bigdata_home }}/{{ installer.ranger }}"
    - name: Unzip Ranger installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.ranger }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete Ranger installer
      file:
        path: "{{ bigdata_home }}/{{ installer.ranger }}"
        state: absent
    - name: Create Ranger symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.ranger.replace('.tar.gz', '') }}"
        dest: "{{ ranger_home }}"
        state: link
    - name: Edit Solr for audit setup
      lineinfile:
        path: "{{ ranger_home }}/contrib/solr_for_audit_setup/install.properties"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        "SOLR_USER": "{{ remote_user }}"
        "SOLR_GROUP": "{{ remote_user }}"
        "SOLR_INSTALL_FOLDER": "{{ solr_home }}"
        "SOLR_RANGER_HOME": "{{ solr_home }}/ranger_audit_server"
        "SOLR_RANGER_PORT": "{{ solr.web_port }}"
        "SOLR_RANGER_DATA_FOLDER": "{{ solr.data_dir }}"
        "SOLR_LOG_FOLDER": "{{ solr_home }}/logs"
        "SOLR_MAX_MEM": "{{ solr.heapsize }}"
    - name: Start Solr
      shell: "./setup.sh"
        chdir: "{{ solr_home }}/contrib/solr_for_audit_setup"

