---

- name: Install CheckProcessExporter
  hosts: bigdata
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    check_process_exporter_home: "{{ bigdata_home }}/check_process_exporter"
    pyenv_home: "/home/{{ remote_user }}/.pyenv"
  tasks:
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/prometheus/{{ installer.check_process_exporter }}"
        dest: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ check_process_exporter_home }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.check_process_exporter }}"
        state: absent
    - name: Create Prometheus symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.check_process_exporter.replace('.zip', '') }}"
        dest: "{{ check_process_exporter_home }}"
        state: link
    - name: Copy configuration file
      template:
        src: "exporter/check-process/{{ item }}"
        dest: "{{ check_process_exporter_home }}/conf/"
        mode: 0644
      with_items:
        - "config.yml"
    - name: Create log directory
      file:
        path: "{{ check_process_exporter_home }}/{{ item }}"
        state: directory
      with_items:
        - "logs"
    - name: Create tmp directory
      file:
        path: "/home/{{ remote_user }}/cpe-tmp"
        state: directory
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/pip/{ installer.psutil }}"
        dest: "/home/{{ remote_user }}/cpe-tmp/"
    - name: Unzip installer
      unarchive:
        src: "/home/{{ remote_user }}/cpe-tmp/{{ installer.psutil }}"
        dest: "/home/{{ remote_user }}/cpe-tmp/"
        remote_src: true
    - name: Install psutil
      pip:
        name: "psutil"
        extra_args: "--no-index -f /home/{{ remote_user }}/cpe-tmp/psutil/psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
        state: present
        executable: "/home/{{ remote_user }}/.pyenv/shims/pip"
    - name: Remove tmp directory
      file:
        dest: "/home/{{ remote_user }}/cpe-tmp"
        state: absent
    - name: Check CheckProcessExporter Process
      shell: "/usr/bin/ps -ef | grep -v grep | grep check_process_exporter.py"
      register: cpe_ps
      failed_when: false
    - name: Start CheckProcessExporter
      shell: "/usr/bin/nohup {{ pyenv_home }}/shims/python {{ check_process_exporter_home }}/check_process_exporter.py -p {{ check_process_exporter.port }} > {{ check_process_exporter_home }}/logs/cp_exporter.log 2>&1 &"
      args:
        chdir: "{{ check_process_exporter_home }}"
      when: '"check_process_exporter" not in cpe_ps.stdout'
