---

- name: Install MariaDB
  hosts: mariadb
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    mariadb_home: "{{ bigdata_home }}/mariadb"
  tasks:
  - name: Create bigdata home directory
    become: yes
    file:
      dest: "{{ bigdata_home }}"
      state: directory
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
  - name: Copy installer
    copy:
      src: "{{ installer_home }}/{{ installer.mariadb }}"
      dest: "{{ bigdata_home }}/{{ installer.mariadb }}"
  - name: Unzip installer
    unarchive:
      src: "{{ bigdata_home }}/{{ installer.mariadb }}"
      dest: "{{ bigdata_home }}/"
      remote_src: true
      owner: "{{ remote_user }}"
      group: "{{ remote_user }}"
  - name: Delete installer
    file:
      path: "{{ bigdata_home }}/{{ installer.mariadb }}"
      state: absent
  - name: Create MariaDB symbolic link
    file:
      src: "{{ bigdata_home }}/{{ installer.mariadb.replace('.tar.gz', '') }}"
      dest: "{{ mariadb_home }}"
      state: link
  - name: Create configuration and log directory
    file:
      path: "{{ mariadb_home }}/{{ item }}"
      state: directory
    with_items:
      - conf
      - logs
  - name: Create configuration file
    template:
      src: mariadb/my.cnf
      dest: "{{ mariadb_home }}/conf/"
      mode: 0644
  - name: Create data directory
    file:
      path: "{{ mariadb.data_dir }}"
      state: directory
  - name: Install MariaDB
    command: "{{ mariadb_home }}/scripts/mysql_install_db --defaults-file={{ mariadb_home }}/conf/my.cnf --user={{ remote_user }}"
  - name: Start MariaDB
    shell: "/usr/bin/nohup {{ mariadb_home }}/bin/mysqld_safe --defaults-file={{ mariadb_home }}/conf/my.cnf --user={{ remote_user }} &"
  - name: Check ncurses library
    stat:
      path: /usr/lib64/libncurses.so.5
    register: nc_result
  - name: Check tinfo library
    stat:
      path: /usr/lib64/libtinfo.so.5
    register: ti_result
  - name: Create ncurses symbolic link
    become: yes
    file:
      src: "/usr/lib64/libncurses.so.6"
      dest: "/usr/lib64/libncurses.so.5"
      state: link
    when: not nc_result.stat.exists
  - name: Create tinfo symbolic link
    become: yes
    file:
      src: "/usr/lib64/libtinfo.so.6"
      dest: "/usr/lib64/libtinfo.so.5"
      state: link
    when: not ti_result.stat.exists
  - name: Get socket dir
    debug: msg="{{ lookup('ansible.builtin.ini', 'socket', type='properties', file='mariadb/my.cnf') }}"
#  - name: Secure installation
#    expect:
#      command: "{{ mariadb_home }}/bin/mysql_secure_installation --basedir={{ mariadb_home }} --defaults-file={{ mariadb_home }}/conf/my.cnf --socket=/mysql.sock --user={{ remote_user }}"
#      responses:
#        'Enter current password for root (enter for none):': "\n"




