- name: Install Zookeeper
  hosts: zookeeper
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zookeeper_home: "{{ bigdata_home }}/zookeeper"
  tasks:
    - name: Create bigdata directory
      become: yes
      become_user: root
      become_method: sudo
      file:
        path: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/zookeeper/{{ installer.zookeeper }}"
        dest: "{{ bigdata_home }}/{{ installer.zookeeper }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.zookeeper }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        creates: "{{ zookeeper_home }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.zookeeper }}"
        state: absent
    - name: Create symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.zookeeper.replace('.tar.gz', '') }}"
        dest: "{{ zookeeper_home }}"
        state: link
      #shell: "ln -s {{ bigdata_home }}/{{ installer.zookeeper.replace('.tar.gz', '') }} {{ bigdata_home }}/zookeeper"
    - name: Create data directory
      file:
        path: "{{ zookeeper_home }}/data"
        state: directory
    - name: Create myid
      copy:
        dest: "{{ zookeeper_home }}/data/myid"
        content: |
          {{ myid }}
    - name: Debug myid
      debug:
        msg: "{{ myid }} > {{ inventory_hostname }}:{{ zookeeper_home }}/data/myid"
    - name: Copy configuration
      copy:
        src: "{{ zookeeper_home }}/conf/zoo_sample.cfg"
        dest: "{{ zookeeper_home }}/conf/zoo.cfg"
    - name: Edit configuration
      lineinfile:
        path: "{{ zookeeper_home }}/conf/zoo.cfg"
        regexp: "^#? *{{ item.key | regex_escape() }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        "tickTime": "{{ zookeeper.tick_time }}"
        "initLimit": "{{ zookeeper.init_limit }}"
        "syncLimit": "{{ zookeeper.sync_limit }}"
        "clientPort": "{{ zookeeper.client_port }}"
        "dataDir": "{{ zookeeper.data_dir }}"
        "4lw.commands.whitelist": "mntr,conf,ruok"
    - name: Edit configuration
      lineinfile:
        path: "{{ zookeeper_home }}/conf/zoo.cfg"
        line: "server.{{ hostvars[item].myid }}={{ item }}:{{ zookeeper.internal_follower_port }}:{{ zookeeper.internal_leader_port }}"
        insertafter: EOF
      with_items: "{{ groups['zookeeper'] }}"
    - name: Check ZooKeeper status
      shell: "{{ zookeeper_home }}/bin/zkServer.sh status"
      register: zk_result
    - name: Start zookeeper server
      shell: "{{ zookeeper_home }}/bin/zkServer.sh start"
      when: >
        ("leader" not in zk_result.stdout)
        and
        ("follower" not in zk_result.stdout)
