---

- name: Install SafeDB
  hosts: safedb, worker, zeppelin
  remote_user: "{{ remote_user }}"
  become: yes
  vars:
  tasks:
    - name: Add SafeDB properties
      template:
        src: "safedb/{{ item }}"
        dest: "/etc/"
        mode: 0664
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
      with_items:
        - "SafeDBAccess.properties"

