---

- name: Install Zeppelin
  hosts: zeppelin
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zeppelin_home: "{{ bigdata_home }}/zeppelin"
  tasks:
    - name: Create bigdata home directory
      become: yes
      file:
        dest: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/zeppelin/{{ installer.zeppelin }}"
        dest: "{{ bigdata_home }}/{{ installer.zeppelin }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.zeppelin }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.zeppelin }}"
        state: absent
    - name: Create Zeppelin symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.zeppelin.replace('.tgz', '') }}"
        dest: "{{ zeppelin_home }}"
        state: link



