---

- name: Install Zeppelin
  hosts: zeppelin
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zeppelin_home: "{{ bigdata_home }}/zeppelin"
  tasks:
    - name: Create bigdata home directory
      become: yes
      file:
        dest: "{{ bigdata_home }}"
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Copy installer
      copy:
        src: "{{ installer_home }}/zeppelin/{{ installer.zeppelin }}"
        dest: "{{ bigdata_home }}/{{ installer.zeppelin }}"
    - name: Unzip installer
      unarchive:
        src: "{{ bigdata_home }}/{{ installer.zeppelin }}"
        dest: "{{ bigdata_home }}/"
        remote_src: true
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
    - name: Delete installer
      file:
        path: "{{ bigdata_home }}/{{ installer.zeppelin }}"
        state: absent
    - name: Create Zeppelin symbolic link
      file:
        src: "{{ bigdata_home }}/{{ installer.zeppelin.replace('.tar.gz', '') }}"
        dest: "{{ zeppelin_home }}"
        state: link
    - name: Add JDBC driver
      copy:
        src: "{{ installer_home }}/jdbc/{{ item }}"
        dest: "{{ zeppelin_home }}/lib/"
      with_items:
        - "{{ installer.mysql_jdbc }}"
        - "{{ installer.ojdbc }}"
    - name: Add JDBC driver
      copy:
        src: "{{ installer_home }}/jdbc/{{ item }}"
        dest: "{{ zeppelin_home }}/interpreter/spark/"
      with_items:
        - "{{ installer.mysql_jdbc }}"
        - "{{ installer.ojdbc }}"
    - name: Add Zeppelin configuration
      template:
        src: "zeppelin/{{ item }}"
        dest: "{{ zeppelin_home }}/conf/"
        mode: 0644
      with_items:
        - zeppelin-site.xml
        - zeppelin-env.sh
        - shiro.ini
    - name: Add library
      copy:
        src: "{{ bigdata_home }}/hbase/lib/"
        dest: "{{ zeppelin_home }}/interpreter/hbase/"
    - name: Start Zeppelin server
      command: "{{ zeppelin_home }}/bin/zeppelin-daemon.sh start"
