- hosts: zookeeper
  remote_user: igkim
  become: no
  tasks:
  - name: Copy installer
    copy:
      src: "{{ installer_home }}/{{ installer.zookeeper }}"
      dest: "{{ bigdata_home }}/{{ installer.zookeeper }}"
  - name: Unzip
    shell: "tar xfz {{ bigdata_home }}/{{ installer.zookeeper }} -C {{ bigdata_home }}/"
  - name: Delete installer
    file:
      path: "{{ bigdata_home }}/{{ installer.zookeeper }}"
      state: absent
  - name: Create symbolic link
    shell: "ln -s {{ bigdata_home }}/{{ installer.zookeeper.replace('.tar.gz', '') }} {{ bigdata_home }}/zookeeper"
  - name: Create data directory
    file:
      path: "{{ bigdata_home }}/zookeeper/data"
      state: directory
  - name: Create myid
    copy:
      dest: "{{ bigdata_home }}/zookeeper/data/myid"
      content: |
        {{ myid }}
  - name: 딛ㄸ디디디디버깅
    debug:
      msg: "{{ myid }} > {{ bigdata_home }}/zookeeper/data/myid"
  - name: Copy configuration
    copy:
      src: "{{ bigdata_home }}/zookeeper/conf/zoo_sample.cfg"
      dest: "{{ bigdata_home }}/zookeeper/conf/zoo.cfg"
  - name: Edit configuration
    lineinfile:
      path: "{{ bigdata_home }}/zookeeper/conf/zoo.cfg"
      regexp: "^#? *{{ item.key | regex_escape() }}="
      line: "{{ item.key }}={{ item.value }}"
    with_dict:
      "clientPort": "{{ zookeeper.client_port }}"
      "dataDir": "{{ zookeeper.data_dir }}"
  - name: Start zookeeper server
    shell: "{{ bigdata_home }}/zookeeper/bin/zkServer.sh start"
