## check_process_exporter configuration

search_list:

  #### Example ###########
  #
  #  example_a:
  #    type: process-name
  #    psname: 'abc'
  #  example_b:
  #    type: cmdline
  #    cmdlist:
  #      - 'bin/bash'
  #      - ''
  #      - 'script.sh'


  node_exporter:
    type: process-name
    psname: 'node_exporter'

  airflow_scheduler:
    type: cmdline
    cmdlist:
      - 'bin/python'
      - 'bin/airflow'
      - 'scheduler'

  airflow_celery_flower:
    type: cmdline
    cmdlist:
      - 'bin/python'
      - 'bin/airflow'
      - 'celery'
      - 'flower'
      - 'D'

  airflow_celery_worker:
    type: cmdline
    cmdlist:
      - 'celery worker -D'