{
 "title": "Bigdata Cluster Service Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "All Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ZooKeeper",
   "type": "stat",
   "description": "ZooKeeper",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-zookeeper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "stat",
   "description": "Kafka",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-kafka\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hadoop-HDFS",
   "type": "stat",
   "description": "Hadoop-HDFS",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-hadoop-hdfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hadoop-YARN",
   "type": "stat",
   "description": "Hadoop-YARN",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-hadoop-yarn\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "description": "MySQL (server-3.novalocal:3306)",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-mysql\", instance=\"server-3.novalocal:3306\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hive",
   "type": "stat",
   "description": "Hive",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-hive\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HBase",
   "type": "stat",
   "description": "HBase",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-hbase\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SparkHistoryServer",
   "type": "stat",
   "description": "SparkHistoryServer (server-3.novalocal:18088)",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-spark\", instance=\"server-3.novalocal:18088\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI for Kafka",
   "type": "stat",
   "description": "UI for Kafka (server-3.novalocal:9000)",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-ufk\", instance=\"server-3.novalocal:9000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hue",
   "type": "stat",
   "description": "Hue (server-3.novalocal:8888)",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-hue\", instance=\"server-3.novalocal:8888\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RStudio",
   "type": "stat",
   "description": "RStudio (server-3.novalocal:8787)",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-rstudio\", instance=\"server-3.novalocal:8787\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zeppelin",
   "type": "stat",
   "description": "Zeppelin (server-3.novalocal:28080)",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-zeppelin\", instance=\"server-3.novalocal:28080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "description": "Redis",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(probe_success{job=\"blackbox-exporter-redis\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow",
   "type": "stat",
   "description": "Airflow",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B + $C + $D + $E +$F +$G", "type": "math" }
   ]
  },
  {
   "title": "Solr",
   "type": "stat",
   "description": "Solr (server-3.novalocal:50076)",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-solr\", instance=\"server-3.novalocal:50076\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ranger",
   "type": "stat",
   "description": "Ranger (server-3.novalocal:50077)",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-exporter-ranger\", instance=\"server-3.novalocal:50077\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZooKeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZooKeeper",
     "type": "stat",
     "description": "ZooKeeper (server-1.novalocal:2181)",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-zookeeper\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka",
     "type": "stat",
     "description": "Kafka (server-1.novalocal:9092)",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-kafka\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hadoop-HDFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "NameNode",
     "type": "stat",
     "description": "NameNode (server-[1-2].novalocal:8020)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-1.novalocal:8020\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-2.novalocal:8020\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JournalNode",
     "type": "stat",
     "description": "JournalNode (server-*.novalocal:8485)",
     "gridPos": { "h": 4, "w": 6, "x": 4, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-1.novalocal:8485\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-2.novalocal:8485\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-3.novalocal:8485\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DataNode",
     "type": "stat",
     "description": "DataNode (server-*.novalocal:9866)",
     "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-1.novalocal:9866\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-2.novalocal:9866\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-hdfs\", instance=\"server-3.novalocal:9866\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hadoop-YARN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "ResourceManager",
     "type": "stat",
     "description": "ResourceManager (server-[2-3].novalocal:8033)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-2.novalocal:8033\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-3.novalocal:8033\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NodeManager",
     "type": "stat",
     "description": "NodeManager (server-*.novalocal:8040)",
     "gridPos": { "h": 4, "w": 6, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-1.novalocal:8040\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-2.novalocal:8040\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-3.novalocal:8040\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JobHistoryServer",
     "type": "stat",
     "description": "JobHistoryServer (server-1.novalocal:10020)",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hadoop-yarn\", instance=\"server-1.novalocal:10020\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Hive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "HiveServer2",
     "type": "stat",
     "description": "HiveServer2 (server-[2-3].novalocal:10000)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hive\", instance=\"server-2.novalocal:10000\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hive\", instance=\"server-3.novalocal:10000\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "HiveMetastore",
     "type": "stat",
     "description": "HiveMetastore (server-[2-3].novalocal:9083)",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hive\", instance=\"server-2.novalocal:9083\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hive\", instance=\"server-3.novalocal:9083\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HBase",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master",
     "type": "stat",
     "description": "Master (server-[1-2].novalocal:60000)",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hbase\", instance=\"server-1.novalocal:60000\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hbase\", instance=\"server-2.novalocal:60000\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "RegionServer",
     "type": "stat",
     "description": "RegionServer (server-*.novalocal:60030)",
     "gridPos": { "h": 4, "w": 6, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-hbase\", instance=\"server-1.novalocal:60030\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hbase\", instance=\"server-2.novalocal:60030\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-hbase\", instance=\"server-3.novalocal:60030\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis-Server",
     "type": "stat",
     "description": "Redis-Server (server-*.novalocal:16379)",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-1.novalocal:16379\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-2.novalocal:16379\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-3.novalocal:16379\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Redis-Sentinel",
     "type": "stat",
     "description": "Redis-Sentinel (server-*.novalocal:26379)",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-1.novalocal:26379\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-2.novalocal:26379\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "probe_success{job=\"blackbox-exporter-redis\", instance=\"server-3.novalocal:26379\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Airflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebServer",
     "type": "stat",
     "description": "WebServer (server-3.novalocal:50073)",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_success{job=\"blackbox-exporter-airflow\", instance=\"server-3.novalocal:50073\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "stat",
     "description": "Scheduler (server-[2-3].novalocal)",
     "gridPos": { "h": 4, "w": 4, "x": 2, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "airflow_scheduler{job=\"check-process-exporter\", instance=\"server-2.novalocal:9439\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "airflow_scheduler{job=\"check-process-exporter\", instance=\"server-3.novalocal:9439\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Celery-Flower",
     "type": "stat",
     "description": "Celery-Flower (server-3.novalocal)",
     "gridPos": { "h": 4, "w": 2, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "airflow_celery_flower{job=\"check-process-exporter\", instance=\"server-3.novalocal:9439\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Celery-Worker",
     "type": "stat",
     "description": "Celery-Worker (server-*.novalocal)",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "airflow_celery_worker{job=\"check-process-exporter\", instance=\"server-1.novalocal:9439\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "airflow_celery_worker{job=\"check-process-exporter\", instance=\"server-2.novalocal:9439\"}",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "airflow_celery_worker{job=\"check-process-exporter\", instance=\"server-3.novalocal:9439\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}