{
 "title": "Bigdata Cluster Resource Usage",
 "tags": [
  "node",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Resource Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{job=\"node-exporter\", mode!='idle'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"node-exporter\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"node-exporter\"} * 100) / node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Used (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 -\n(\n    (sum by (instance)(node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"tmpfs\"}) * 100)\n    /\n    (sum by (instance)(node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"tmpfs\"}))\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "\bDisk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{job=\"node-exporter\", device=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "(read) {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_written_bytes_total{job=\"node-exporter\", device=~\"$diskdevices\"}[$__rate_interval]))",
     "legendFormat": "(write) {{instance}}"
    }
   ]
  },
  {
   "title": "\bNetwork I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_network_receive_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8)",
     "legendFormat": "(in) {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{job=\"node-exporter\"}[$__rate_interval])*8)",
     "legendFormat": "(out) {{instance}}"
    }
   ]
  }
 ]
}