- name: Stop history server
  hosts: spark-history
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    spark_home: "{{ bigdata_home }}/spark"
  tasks:
    - name: Check history server in jps
      command: "/usr/bin/jps"
      register: hs_jps
      changed_when: False
    - name: Stop history server
      command: "{{ spark_home }}/sbin/stop-history-server.sh"
      when: '"HistoryServer" in hs_jps.stdout'