---

- name: Stop httpfs
  hosts: httpfs
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop httpfs"

- name: Stop JobHistory Server
  hosts: jobhistoryserver
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/mapred --daemon stop historyserver"

- name: Stop NodeManager
  hosts: nodemanager
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon stop nodemanager"

- name: Stop ResourceManager
  hosts: resourcemanager
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon stop resourcemanager"

- name: Stop DataNode
  hosts: datanode
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop DataNode
      command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop datanode"
      failed_when: False

- name: Stop Active NameNode
  hosts: "{{ groups['namenode'][0] }}"
  become: no
  tasks:
    - name: Stop NameNode, JournalNode, ZKFC
      command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/sbin/stop-dfs.sh"
      failed_when: False
