---

### Stop Celery
#- name: Stop Celery flower
#  hosts: airflow-webserver
#  remote_user: "{{ remote_user }}"
#  become: no
#  tasks:
#    - name: Stop Celery flower
#      command: "~/.pyenv/shims/airflow celery flower -D"

## Stop Webserver
- name: Stop Airflow webserver
  hosts: airflow-webserver:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Stop Airflow webserver
      shell: "/usr/bin/kill -9 `cat {{ airflow_home }}/airflow-webserver.pid`"
      failed_when: false
    - name: Remove pid file
      shell: "/usr/bin/rm {{ airflow_home }}/airflow-webserver.pid"
      failed_when: false
    - name: Kill airflow worker process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep 'airflow-webserver' | grep -v grep | awk '{print $2}')"
      failed_when: false


## Stop Scheduler
- name: Stop Airflow scheduler
  hosts: airflow-scheduler:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Stop Airflow scheduler
      shell: "/usr/bin/kill -9 `cat {{ airflow_home }}/airflow-scheduler.pid`"
      failed_when: false
    - name: Remove pid file
      shell: "/usr/bin/rm {{ airflow_home }}/airflow-scheduler.pid"
      failed_when: false
    - name: Kill airflow scheduler process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep 'airflow scheduler' | grep -v grep | awk '{print $2}')"
      failed_when: false
    - name: Kill airflow worker process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep 'airflow worker' | grep -v grep | awk '{print $2}')"
      failed_when: false
    - name: Kill airflow executor process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep 'airflow executor' | grep -v grep | awk '{print $2}')"
      failed_when: false


## Stop Celery Flower
- name: Stop Celery flower
  hosts: airflow-celery-flower:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Stop Celery flower
      shell: "/usr/bin/kill -9 `cat {{ airflow_home }}/airflow-flower.pid`"
      failed_when: false
    - name: Remove pid file
      shell: "/usr/bin/rm {{ airflow_home }}/airflow-flower.pid"
      failed_when: false
    - name: Kill Celery flower process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep -v grep | grep 'airflow celery flower' | awk '{print $2}')"
      failed_when: false


## Stop Celery Worker
- name: Stop Celery worker
  hosts: airflow-celery-worker:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Stop Celery worker
      shell: "/usr/bin/kill -9 `cat {{ airflow_home }}/airflow-worker.pid`"
      failed_when: false
    - name: Remove pid file
      shell: "/usr/bin/rm {{ airflow_home }}/airflow-worker.pid"
      failed_when: false
    - name: Kill Celery worker process
      shell: "/usr/bin/kill -9 $(/usr/bin/ps -ef | grep -v grep | grep 'celery worker' | grep 'MainProcess' | awk '{print $2}')"
      failed_when: false