---

- name: Stop MySQL
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Start MySQL
      command: "{{ mysql.home_dir }}/bin/mysqladmin --defaults-file={{ mysql.home_dir }}/conf/my.cnf -u root shutdown"