---

- name: Stop Grafana
  hosts: grafana
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    grafana_home: "{{ bigdata_home }}/grafana"
  tasks:
    - name: Check grafana process
      shell: "/usr/bin/ps -ef | grep 'grafana server' | grep -v grep | awk '{print $2}'"
      register: grafana_pid
      failed_when: false
    - name: Stop Grafana
      shell: "/usr/bin/kill -9 {{ grafana_pid.stdout }}"
      when: grafana_pid != ""

