- name: Stop Zookeeper
  hosts: zookeeper:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zookeeper_home: "{{ bigdata_home }}/zookeeper"
  tasks:
    - name: Check ZooKeeper status
      shell: "{{ zookeeper_home }}/bin/zkServer.sh status"
      register: zk_result
      failed_when: false
    - name: Stop zookeeper server
      shell: "{{ zookeeper_home }}/bin/zkServer.sh stop"
      when: >
        ("leader"  in zk_result.stdout)
        or
        ("follower"  in zk_result.stdout)