---

- name: Stop MySQL
  hosts: mysql:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop MySQL
      command: "{{ mysql.home_dir }}/bin/mysqladmin --defaults-file={{ mysql.home_dir }}/conf/my.cnf -uroot -p{{ mysql.root_pw }} shutdown"
      register: stopper
      failed_when: >
        (
          ("Check that mysqld is running" not in stopper.stderr)
          and
          ("Using a password on the command line interface can be insecure." not in stopper.stderr)
        )
        and
        (stopper.stderr !="")