---

- name: Stop NodeManager
  hosts: nodemanager:worker:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon stop nodemanager"
    - name: Check NodeManager pid
      shell: "/usr/bin/jps | grep 'NodeManager' | awk '{print $1}'"
      register: nm_pid
      failed_when: false
    - name: Kill NodeManager
      command: "/usr/bin/kill -9 {{ nm_pid.stdout }}"
      when: nm_pid.stdout != ""
