---

- name: Stop NodeExporter
  hosts: node-exporter:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    node_exporter_home: "{{ bigdata_home }}/node_exporter"
  tasks:
    - name: Find NodeExporter process ID
      shell: "/usr/bin/ps -ef | grep -v grep | grep node_exporter | awk '{print $2}'"
      register: node_exporter_pid
      failed_when: false
    - name: Kill NodeExporter
      command: "/usr/bin/kill -9 {{ node_exporter_pid.stdout }}"
      when: node_exporter_pid.stdout !=""