---

- name: Stop JobHistory Server
  hosts: jobhistoryserver:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/mapred --daemon stop historyserver"
    - name: Check JobHistory Server pid
      shell: "/usr/bin/jps | grep 'JobHistoryServer' | awk '{print $1}'"
      register: hs_pid
      failed_when: false
    - name: Kill JobHistory Server
      command: "/usr/bin/kill -9 {{ hs_pid.stdout }}"
      when: hs_pid.stdout != ""
