---

- name: Stop DataNode
  hosts: datanode:worker:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop DataNode
      command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop datanode"
      failed_when: False
    - name: Check DataNode pid
      shell: "/usr/bin/jps | grep 'DataNode' | awk '{print $1}'"
      register: dn_pid
      failed_when: false
    - name: Kill DataNode
      command: "/usr/bin/kill -9 {{ dn_pid.stdout }}"
      when: dn_pid.stdout != ""
