---

- name: Stop Kafka
  hosts: kafka:&{{ variable_host }}
  become: no
  vars:
    kafka_home: "{{ bigdata_home }}/kafka"
  tasks:
    - name: Stop Kafka cluster
      command: "{{ kafka_home }}/bin/kafka-server-stop.sh"
      register: stop_result
      failed_when: >
        ("No kafka server to stop" not in stop_result.stderr)
        and
        (stop_result.stderr != "")