---

- name: Stop RStudio
  hosts: R:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Stop RStudio
      become: yes
      command: "systemctl stop rstudio-server"