---

- name: Start UFK server
  hosts: ufk:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: yes
  vars:
    ufk_home: "{{ bigdata_home }}/kafka-ui"
  tasks:
    - name: Check UFK ps
      become: yes
      shell: "/usr/bin/docker compose -f {{ ufk_home }}/docker-compose.yml ps -a | grep kafka-ui | grep ago | grep Up"
      register: ufk_ps
      failed_when: false
    - name: Start UFK server
      command: "/usr/bin/docker compose -f {{ ufk_home }}/docker-compose.yml up -d"
      when: '"kafka-ui" not in ufk_ps.stdout'