---

- name: Start HBase all component
  hosts: "{{ groups['hbase-master'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Start master process
      shell: "/usr/bin/nohup {{ hbase_home }}/bin/start-hbase.sh"

## 미사용으로 인한 임시 제거
#    - name: Start thrift server
#      shell: "{{ hbase_home }}/bin/hbase-daemon.sh start thrift"