---

- name: Start HBase all component
  hosts: "{{ groups['hbase-master'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Start master process
      shell: "/usr/bin/nohup {{ hbase_home }}/bin/start-hbase.sh"