---

- name: Start RStudio
  hosts: R:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: yes
  tasks:
    - name: Start RStudio
      become: yes
      command: "systemctl start rstudio-server"