---

- name: Start HCatalog server
  hosts: metastore
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hive_home: "{{ bigdata_home }}/hive"
  tasks:
    - name: Check HCtalog process
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'hive.metastore.HiveMetaStore'"
      register: meta_ps
      changed_when: false
    - name: Start HCatalog server
      command: "{{ hive_home }}/hcatalog/sbin/hcat_server.sh start"
      when: '"hive.metastore.HiveMetaStore" not in meta_ps.stdout'

- name: Start HiveServer2
  hosts: hive-server2
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hive_home: "{{ bigdata_home }}/hive"
  tasks:
    - name: Check HiveServer2 process
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'hive.service.server.HiveServer2'"
      register: hs_ps
      changed_when: false
    - name: Start HiveServer2
      shell: "/usr/bin/nohup {{ hive_home }}/bin/hiveserver2 > /dev/null 2>&1 &"
      when: '"hive.service.server.HiveServer2" not in hs_ps.stdout'