---

## 2023. 06. 20. 스크립트 동작 이상으로 인한 개별 중지로 변경
#- name: Start HBase all component
#  hosts: "{{ groups['hbase-master'][0] }}"
#  remote_user: "{{ remote_user }}"
#  become: no
#  vars:
#    hbase_home: "{{ bigdata_home }}/hbase"
#  tasks:
#    - name: Start master process
#      shell: "/usr/bin/nohup {{ hbase_home }}/bin/start-hbase.sh"

- name: Start HBase Master
  hosts: "{{ groups['hbase-master'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Start HBase Master
      shell: "/usr/bin/nohup {{ hbase_home }}/bin/hbase-daemon.sh start master"
      when: '"HMaster" not in hm_result.stdout'

- name: Start HBase Master
  hosts: "{{ groups['hbase-master'][1:] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Start HBase Master
      shell: "/usr/bin/nohup {{ hbase_home }}/bin/hbase-daemon.sh start master"
      when: '"HMaster" not in hm_result.stdout'

- name: Start HBase RegionServer
  hosts: worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Check HBase RegionServer
      shell: "/usr/bin/jps | grep 'HRegionServer'"
      register: rs_result
      failed_when: false
    - name: Start HBase RegionServer
      shell: "/usr/bin/nohup {{ hbase_home }}/bin/hbase-daemon.sh start regionserver"
      when: '"HRegionServer" not in rs_result.stdout'