---

- name: Start Redis server
  hosts: redis:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    redis_home: "{{ bigdata_home }}/redis"
  tasks:
    - name: Check Redis Server process
      shell: "/usr/bin/ps -ef | grep -v grep | grep redis-server | grep {{ redis.port }}"
      register: redis_ps
      failed_when: false
    - name: Start Redis Server
      command: "{{ redis_home }}/bin/redis-server {{ redis_home }}/conf/redis.conf"
      when: '"redis-server" not in redis_ps.stdout'
    - name: Check Redis Sentinel process
      shell: "/usr/bin/ps -ef | grep -v grep | grep redis-sentinel | grep {{ redis.sentinel_port }}"
      register: redis_sentinel_ps
      failed_when: false
    - name: Start Redis Sentinel server
      command: "{{ redis_home }}/bin/redis-sentinel {{ redis_home }}/conf/sentinel.conf"
      when: '"redis-sentinel" not in redis_sentinel_ps.stdout'