- name: Start history server
  hosts: spark-history
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    spark_home: "{{ bigdata_home }}/spark"
  tasks:
    - name: Check History server jps
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'spark.deploy.history.HistoryServer'"
      register: hs_ps
      failed_when: false
    - name: Start History server
      command: "{{ spark_home }}/sbin/start-history-server.sh"
      when: '"spark.deploy.history.HistoryServer" not in hs_ps.stdout'