- name: Start history server
  hosts: spark-history
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    spark_home: "{{ bigdata_home }}/spark"
  tasks:
    - name: Check history server in jps
      command: "/usr/bin/jps"
      register: hs_jps
    - name: Start history server
      command: "{{ spark_home }}/sbin/start-history-server.sh"
      when: '"HisstoryServer not in hs_jps.stdout'