---

- name: Start Hue server
  hosts: hue
  remote_user: "{{ remote_user }}"
  become: yes
  vars:
    hue_home: "{{ bigdata_home }}/hue"
  tasks:
    - name: Check Hue process
      shell: "/usr/bin/docker compose -f {{ hue_home }}/docker-compose.yml ps -a | grep hue | grep ago | grep Up"
      register: hue_ps
      failed_when: false
    - name: Start Hue server
      command: "/usr/bin/docker compose -f {{ hue_home }}/docker-compose.yml up -d"
      when: '"hue-server" not in hue_ps.stdout'