- name: Start Zookeeper
  hosts: zookeeper
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Start zookeeper server
      shell: "{{ bigdata_home }}/zookeeper/bin/zkServer.sh start"
      register: start_zoo
    - name: Debug zookeeper server
      debug: var=start_zoo
    - name: Get zookeeper server status
      shell: "{{ bigdata_home }}/zookeeper/bin/zkServer.sh status"
      register: status_zoo
    - name: Debug zookeeper status
      debug: var=status_zoo