- name: Start Zookeeper
  hosts: zookeeper
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zookeeper_home: "{{ bigdata_home }}/zookeeper"
  tasks:
    - name: Check ZooKeeper status
      shell: "{{ zookeeper_home }}/bin/zkServer.sh status"
      register: zk_result
    - name: Start zookeeper server
      shell: "{{ zookeeper_home }}/bin/zkServer.sh start"
      when: >
        ("leader" not in zk_result.stdout)
        and
        ("follower" not in zk_result.stdout)


