---

- name: Start NodeExporter
  hosts: node-exporter
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    node_exporter_home: "{{ bigdata_home }}/node_exporter"
  tasks:
    - name: Check NodeExporter PID
      shell: "/usr/bin/ps -ef | grep node_exporter | grep -v grep"
      register: ne_pid
      failed_when: false
    - name: Start NodeExporter
      shell: "/usr/bin/nohup {{ node_exporter_home }}/node_exporter > {{ node_exporter_home }}/logs/node_exporter.log 2>&1 &"
      when: '"node_exporter" not in ne_pid'