---

- name: Start MySQL
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Check MySQL ps
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'mysqld' | grep 'port={{ mysql.jdbc_port }}'"
      register: mysql_ps
    - name: Start MySQL
      shell: "/usr/bin/nohup {{ mysql.home_dir }}/bin/mysqld_safe --defaults-file={{ mysql.home_dir }}/conf/my.cnf --user={{ remote_user }} &"
      when: '"mysqld" not in mysql_ps.stdout'