
- name: Start ResourceManager
  hosts: resourcemanager:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Check ResourceManager jps
      command: "/usr/bin/jps"
      register: rm_jps
      failed_when: False
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon start resourcemanager"
      when: '"ResourceManager" not in rm_jps.stdout'
