---

- name: Start MariaDB
  hosts: mariadb
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Start MariaDB server
      shell: "/usr/bin/nohup {{ mariadb.home_dir }}/bin/mysqld_safe --defaults-file={{ mariadb.home_dir }}/conf/my.cnf --user={{ remote_user }} &"
