---

- name: Install CMAK
  hosts: cmak
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    cmak_home: "{{ bigdata_home }}/cmak"
  tasks:
    - name: Start CMAK
      command: "/usr/bin/nohup {{ cmak_home }}/bin/cmak"