---

- name: Start Ranger
  hosts: ranger
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    solr_home: "{{ bigdata_home }}/solr"
    ranger_home: "{{ bigdata_home }}/ranger"
  tasks:
    - name: Check Solr server ps
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'solr' | grep 'start.jar' | grep 'jetty.port={{ ranger.solr.web_port }}'"
      register: solr_ps
      failed_when: false
    - name: Start Solr
      shell: "./start_solr.sh"
      args:
        chdir: "{{ solr_home }}/ranger_audit_server/scripts"
      when: '"solr" not in solr_ps.stdout'
    - name: Check Ranger server ps
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'org.apache.ranger.server.tomcat.EmbeddedServer'"
      register: ranger_ps
      failed_when: false
    - name: Start Ranger server
      shell: "./ranger-admin-services.sh start"
      args:
        chdir: "{{ ranger_home }}/ews"
      when: '"ranger" not in ranger_ps.stdout'