---

## Start Scheduler
- name: Start Airflow scheduler
  hosts: airflow-scheduler:&{{ variable_host }}
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Check Airflow scheduler
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'bin/airflow scheduler'"
      register: scheduler_result
      failed_when: false
    - name: Remove pid file
      file:
        path: "{{ airflow_home }}/airflow-scheduler.pid"
        state: absent
      when: '"airflow scheduler" not in scheduler_result.stdout'
    - name: Start Airflow scheduler
      command: "~/.pyenv/shims/airflow scheduler -D"
      when: '"airflow scheduler" not in scheduler_result.stdout'
