---

## 2023. 06. 20. 스크립트 동작 이상으로 인한 개별 중지로 변경
#- name: Start HBase all component
#  hosts: "{{ groups['hbase-master'][0] }}"
#  remote_user: "{{ remote_user }}"
#  become: no
#  vars:
#    hbase_home: "{{ bigdata_home }}/hbase"
#  tasks:
#    - name: Start master process
#      shell: "/usr/bin/nohup {{ hbase_home }}/bin/start-hbase.sh"

- name: Start HBase Master
  hosts: hbase-master
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Start HBase Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"

- name: Start HBase RegionServer
  hosts: worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Start HBase RegionServer
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start regionserver"