version: '3'

services:
  hue-server:
    image: daou/hue:4.10.3
    hostname: hue
    network_mode: host
    container_name: hue-4.10.3
    ports:
      - "{{ hue.web_port }}:8888"
    volumes:
      - ./conf/hue.ini:/usr/share/hue/desktop/conf/z-hue-z.ini