############################################
# 2024-02-13
# Bigdata Cluster 구축용 Host 설정 파일
#
# 운영 장비용
############################################

### 2023.08.16
# FQDN으로 작성, Alias 사용 금지

bigdata:
  hosts:
    # Cluster all hosts

  children:

    ## Worker Node
    #  (DataNode, NodeManager, RegionServer, Spark, NodeExporter가 설치될 Node)
    worker:
      hosts:


    ## Scale-in (Scale-out의 경우 해당 목록에서 제거)
    scale-in:
      hosts:


    ## ZooKeeper Cluster
    zookeeper:
      hosts:


    ## Hadoop Cluster
    hadoop:
      hosts:
      children:
        namenode:
          hosts:

        # Use worker instead of datanode.
        datanode:
        journalnode:
          hosts:

        resourcemanager:
          hosts:

        # Use worker instead of nodemanager.
        nodemanager:
        jobhistoryserver:
          hosts:

        httpfs:
          hosts:

        client:
          hosts:


    ## Kafka Cluster
    kafka:
      hosts:


    ## pyenv
    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:


    ## MariaDB Server
    # pyenv 설치 필요
    mariadb:
      hosts:

#          ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

    ## MySQL Server
    # pyenv 설치 필요
    mysql:
      hosts:


    ## Hive Server
    # MariaDB 설치 필요
    hive:
      children:
        hive-server2:
          hosts:

        metastore:
          hosts:


    ## Spark
    # Use worker instead of spark.
    spark:
      children:
        spark-history:
          hosts:


    ## HBase Cluster
    hbase:
      hosts:
      children:
        hbase-master:
          hosts:

        # Use worker instead of region-server.
        region-server:

    ## Hue Server
    hue:
      hosts:


    ## Sqoop client
    sqoop:
      hosts:


    ## UI for Apache Kafka Web Server
    ufk:
      hosts:


    ## Airflow
    airflow:
      hosts:
      children:
        airflow-webserver:
          hosts:

        airflow-scheduler:
          hosts:

        airflow-celery-flower:
          hosts:

        airflow-celery-worker:
          hosts:


    ## Zeppelin
    zeppelin:
      hosts:


    ## Redis Sentinel Cluster (3대로 구성)
    redis:
      hosts:


    R:
      hosts:


    prometheus:
      hosts:


    # Use all hosts.
    node-exporter:
      hosts:

    blackbox-exporter:
      hosts:


    check-process-exporter:
      hosts:


    kminion-exporter:
      hosts:


    grafana:
      hosts:


    ranger:
      hosts:


    safedb:
      hosts:
