- name: Setup Active NameNode
  hosts: "{{ groups['namenode'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Check already format (1/n)
      stat:
#        path: "{{ hadoop.hdfs.namenode_dir[0] }}/current/VERSION"
        path: "/home/bigdata/igkim/a"
      register: version_result
    - name: Check already format (2/n)
      stat:
#        path: "{{ hadoop.hdfs.namenode_dir[0] }}/in_use.lock"
        path: "/home/bigdata/igkim/b"
      register: lock_result
    - name: 둘 다 없으면 실행
      debug:
        msg: 파일이 둘 다 없으므로 포맷
      when: >
        (not version_result.stat.exists)
        and
        (not lock_result.stat.exists)
    - name: False
      debug:
        msg:
          - "{{ version_result }}"
          - "{{ lock_result }}"
