---

- name: Check Zeppelin status
  hosts: zeppelin
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zeppelin_home: "{{ bigdata_home }}/zeppelin"
  tasks:
    - name: Set default status
      set_fact:
        cacheable: yes
        zep_status: "Zeppelin is stopped."
      no_log: true
    - name: Check Zeppelin
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'zeppelin.server.ZeppelinServer'"
      register: zep_ps
      no_log: true
      failed_when: false
    - name: Set status
      set_fact:
        cacheable: yes
        zep_status: "Zeppelin is running."
      when: '"zeppelin" in zep_ps.stdout'
      no_log: true
    - name: Show Zeppelin status
      debug:
        msg:
          - "{{ zep_status }}"