---

- name: Check RStudio status
  hosts: R
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Show RStudio status
      become: yes
      command: "systemctl status rstudio-server"
      failed_when: false