---

- name: Check Zookeeper status
  hosts: zookeeper
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    zookeeper_home: "{{ bigdata_home }}/zookeeper"
  tasks:
    - name: Set default status
      set_fact:
        cacheable: yes
        zk_status: "Zookeeper is stopped."
      no_log: true
    - name: Check Zookeeper
      shell: "{{ zookeeper_home }}/bin/zkServer.sh status"
      register: zk_status
      no_log: true
      failed_when: false
    - name: Set status
      set_fact:
        cacheable: yes
        zk_status: "Zookeeper is running."
      when: >
        ("leader" in zk_status.stdout)
        or
        ("follower" in zk_status.stdout)
      no_log: true
    - name: Show Zookeeper status
      debug:
        msg:
          - "{{ zk_status }}"