- name: Uninstall MySQL
  hosts: mysql
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop MySQL server
      command: "{{ mysql.home_dir }}/bin/mysqladmin --defaults-file={{ mysql.home_dir }}/conf/my.cnf -u root shutdown"
      failed_when: False
    - name: Remove directory
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ mysql.home_dir }}"
        - "{{ mysql.data_dir }}"
        - "{{ mysql.home_dir.replace('/mariadb','') }}/{{ installer.mariadb.replace('.tar.xz', '') }}"
