---

- name: Stop history server
  hosts: spark-history
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    spark_home: "{{ bigdata_home }}/spark"
  tasks:
    - name: Find History server process ID
      shell: "/usr/bin/ps -ef | grep -v grep | grep 'spark.deploy.history.HistoryServer' | awk '{print $2}'"
      register: hs_pid
      failed_when: false
    - name: Stop History server
      shell: "/usr/bin/kill -9 {{ hs_pid.stdout }}"
      when: hs_pid.stdout !=""

- name: Delete HDFS directory
  hosts: "{{ groups['worker'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hadoop_home: "{{ bigdata_home }}/hadoop"
  tasks:
    - name: Delete Spark archive directory
      command: "{{ hadoop_home }}/bin/hdfs dfs -rm -r -f /spark/archive"
      failed_when: False
    - name: Delete Spark log directory
      command: "{{ hadoop_home }}/bin/hdfs dfs -rm -r -f /spark-logs"
      failed_when: False

- name: Uninstall Spark
  hosts: bigdata, worker
  become: no
  vars:
    spark_home: "{{ bigdata_home }}/spark"
  tasks:
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.spark.replace('.tgz', '') }}"
        - "{{ spark_home }}"
      failed_when: False
