---

- name: Remove HBase directory
  hosts: hbase
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.hbase.replace('-bin.tar.gz', '') }}"
        - "{{ hbase_home }}"
      failed_when: False
