---

- name: Uninstall Grafana
  hosts: grafana
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    grafana_home: "{{ bigdata_home }}/grafana"
  tasks:
    - name: Check grafana process
      shell: "/usr/bin/ps -ef | grep 'grafana server web' | grep -v grep | awk '{print $2}'"
      register: grafana_pid
      failed_when: false
    - name: Stop Grafana
      shell: "/usr/bin/kill -9 {{ grafana_pid.stdout }}"
      when: grafana_pid != ""
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.grafana.replace('.tar.gz', '') }}"
        - "{{ grafana_home }}"
      failed_when: False

