---

- name: Uninstall Ranger
  hosts: ranger
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    solr_home: "{{ bigdata_home }}/solr"
    ranger_home: "{{ bigdata_home }}/ranger"
  tasks:
    - name: Check Ranger process
      shell: "/usr/bin/ps -ef | grep 'org.apache.ranger.server.tomcat.EmbeddedServer' | grep -v grep | awk '{print $2}'"
      register: ranger_pid
      failed_when: false
    - name: Stop Ranger
      shell: "/usr/bin/kill -9 {{ ranger_pid.stdout }}"
      when: ranger_pid.stdout != ""
    - name: Check Solr process
      shell: "/usr/bin/ps -ef | grep 'solr' | grep -v grep | grep 'jetty.port={{ ranger.solr.web_port }}' | awk '{print $2}'"
      register: solr_pid
      failed_when: false
    - name: Stop Solr
      shell: "/usr/bin/kill -9 {{ solr_pid.stdout }}"
      when: solr_pid.stdout != ""
    - name: Remove directory
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.solr.replace('.tgz', '') }}"
        - "{{ solr_home }}"
        - "{{ ranger.solr.data_dir }}"
        - "{{ bigdata_home }}/{{ installer.ranger_admin.replace('.tar.gz', '') }}"
        - "{{ ranger_home }}"
      failed_when: False

