---

- name: Stop Airflow Service
  hosts: airflow-webserver
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "/home/{{ remote_user }}/airflow"
  tasks:
    - name: Stop Airflow webserver
      command: ""
      failed_when: False

- name: Uninstall Airflow
  hosts: airflow-webserver
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "/home/{{ remote_user }}/airflow"
  tasks:
    - name: Uninstall Airflow
      command: "pip uninstall apache-airflow[celery] -y"

- name: Remove Airflow directory
  hosts: airflow-webserver
  become: no
  vars:
    airflow_home: "/home/{{ remote_user }}/airflow"
  tasks:
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ remote_user }}/airflow"
        - "/home/{{ remote_user }}/airflow-tmp"
      failed_when: False