---

- name: Uninstall Prometheus
  hosts: prometheus
  become: no
  vars:
    prometheus_home: "{{ bigdata_home }}/prometheus"
  tasks:
    - name: Find Prometheus process ID
      shell: "/usr/bin/ps -ef | grep prometheus | grep -v grep | grep {{ prometheus.web_port }} | awk '{print $2}'"
      register: prometheus_pid
      failed_when: false
    - name: Kill Prometheus
      command: "/usr/bin/kill -9 {{ prometheus_pid.stdout }}"
      when: prometheus_pid.stdout !=""
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.prometheus.replace('.tar.gz', '') }}"
        - "{{ prometheus_home }}"
      failed_when: False

- name: Uninstall NodeExporter
  hosts: node-exporter
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    node_exporter_home: "{{ bigdata_home }}/node_exporter"
  tasks:
    - name: Find NodeExporter process ID
      shell: "/usr/bin/ps -ef | grep node_exporter | grep -v grep | awk '{print $2}'"
      register: node_exporter_pid
      failed_when: false
    - name: Kill NodeExporter
      command: "/usr/bin/kill -9 {{ node_exporter_pid.stdout }}"
      when: node_exporter_pid.stdout !=""
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.node_exporter.replace('.tar.gz', '') }}"
        - "{{ node_exporter_home }}"
      failed_when: False