---

- name: Uninstall KMinionExporter
  hosts: kminion-exporter
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    kminion_exporter_home: "{{ bigdata_home }}/kminion_exporter"
  tasks:
    - name: Find KMinionExporter process ID
      shell: "/usr/bin/ps -ef | grep -v grep | grep {{ kminion_exporter_home }}/bin/kminion | awk '{print $2}'"
      register: ke_pid
      failed_when: false
    - name: Kill KMinionExporter
      command: "/usr/bin/kill -9 {{ ke_pid.stdout }}"
      when: ke_pid.stdout !=""
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ kminion_exporter_home }}"
      failed_when: False