---

- name: Uninstall Ranger Plugins
  hosts: namenode
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
  tasks:
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_hdfs.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/hdfs"
      failed_when: False

