- name: Uninstall MariaDB
  hosts: mariadb
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    mariadb_home: "{{ bigdata_home }}/mariadb"
  tasks:
  - name: Stop MariaDB server
    command: "{{ mariadb_home }}/bin/mysqladmin shutdown --socket={{ mariadb_home }}/mysql.sock "
  - name: Remove directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ mariadb_home }}"
    - "{{ mariadb.data_dir }}"
    - "{{ bigdata_home }}/{{ installer.mariadb.replace('.tar.gz', '') }}"
