---

- name: Uninstall Ranger-HDFS Plugins
  hosts: namenode
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hdfs_plugin_home: "{{ plugin_home }}/hdfs"
  tasks:
    - name: Disable Ranger HDFS Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hdfs_plugin_home }}/disable-hdfs-plugin.sh"
      failed_when: False
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_hdfs.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/hdfs"
      failed_when: False

- name: Uninstall Ranger-YARN Plugins
  hosts: resourcemanager
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    yarn_plugin_home: "{{ plugin_home }}/yarn"
  tasks:
    - name: Disable Ranger YARN Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ yarn_plugin_home }}/disable-yarn-plugin.sh"
      failed_when: False
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_yarn.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/yarn"
      failed_when: False

- name: Uninstall Ranger-Hive Plugins
  hosts: hive-server2
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hive_plugin_home: "{{ plugin_home }}/hive"
  tasks:
    - name: Disable Ranger Hive Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hive_plugin_home }}/disable-hive-plugin.sh"
      failed_when: False
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_hive.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/hive"
      failed_when: False

- name: Uninstall Ranger-HBase Plugins
  hosts: hbase, worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
    hbase_plugin_home: "{{ plugin_home }}/hive"
  tasks:
    - name: Disable Ranger HBase Plugin
      become: yes
      shell: "export JAVA_HOME=\"{{ java_home }}\" && sh {{ hive_plugin_home }}/disable-hbase-plugin.sh"
      failed_when: False
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_hbase.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/hbase"
      failed_when: False

