---

#- name: Uninstall Journalnode
#  hosts: journalnode
#  remote_user: "{{ remote_user }}"
#  become: no
#  tasks:
#  - name: Stop journalnode
#    command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop journalnode"

- name: Uninstall httpfs
  hosts: "{{ groups['namenode'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop httpfs"


- name: Uninstall JobHistory Server
  hosts: jobhistoryserver
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/mapred --daemon stop historyserver"

- name: Uninstall NodeManager
  hosts: nodemanager
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon stop nodemanager"

- name: Uninstall ResourceManager
  hosts: resourcemanager
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/yarn --daemon stop resourcemanager"

- name: Uninstall DataNode
  hosts: datanode
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop DataNode
      command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/bin/hdfs --daemon stop datanode"
      failed_when: False

- name: Uninstall Active NameNode
  hosts: "{{ groups['namenode'][0] }}"
  become: no
  tasks:
    - name: Stop NameNode, JournalNode, ZKFC
      command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/sbin/stop-dfs.sh"
      failed_when: False
    - name: Remove ZKFC directory
      command: "{{ bigdata_home }}/zookeeper/bin/zkCli.sh -server {{ groups['namenode'][0] }}:{{ zookeeper.client_port }} deleteall /hadoop-ha"
      failed_when: False

# 전체 삭제는 좀 아닌듯
- name: Remove directory
  hosts: hadoop
  become: no
  tasks:
    - name: Wait
      pause:
        seconds: 5
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.hadoop.replace('.tar.gz', '') }}"
        - "{{ bigdata_home }}/hadoop"
#        - "{{ hadoop.hdfs.namenode_dir }}"
#        - "{{ hadoop.hdfs.datanode_dir}}"
#        - "{{ hadoop.hdfs.journalnode_dir }}"
      failed_when: False
