---

- name: Uninstall Ranger
  hosts: ranger
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    solr_home: "{{ bigdata_home }}/solr"
    ranger_home: "{{ bigdata_home }}/ranger"
  tasks:
    - name: Check Ranger process
      shell: "/usr/bin/ps -ef | grep 'ranger' | grep -v grep | awk '{print $2}'"
      register: ranger_pid
      failed_when: false
    - name: Stop Grafana
      shell: "/usr/bin/kill -9 {{ ranger_pid.stdout }}"
      when: ranger_pid != ""
    - name: Check Solr process
      shell: "/usr/bin/ps -ef | grep 'solr' | grep -v grep | awk '{print $2}'"
      register: solr_pid
      failed_when: false
    - name: Stop Solr
      shell: "/usr/bin/kill -9 {{ solr_pid.stdout }}"
      when: solr_pid != ""
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.solr.replace('.tgz', '') }}"
        - "{{ solr_home }}"
        - "{{ solr.data_dir }}"
        - "{{ bigdata_home }}/{{ installer.ranger_admin.replace('.tar.gz', '') }}"
        - "{{ ranger_home }}"
      failed_when: False

