---

#- name: Uninstall Active NameNode
#  hosts: "{{ groups['namenode'][0] }}"
#  become: no
#  tasks:
#  - name: Stop NameNode, JournalNode, ZKFC
#    command: "/usr/bin/nohup {{ bigdata_home }}/hadoop/sbin/stop-dfs.sh"
#    failed_when: False
#  - name: Remove ZKFC directory
#    command: "{{ bigdata_home }}/zookeeper/bin/zkCli.sh -server {{ groups['namenode'][0] }}:{{ zookeeper.client_port }} deleteall /hadoop-ha"
#    failed_when: False

- name: Delete Test Topic
  hosts: "{{ groups['kafka'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    kafka_home: "{{ bigdata_home }}/kafka"
  tasks:
    - name: Delete topic
      command: "{{ kafka_home }}/bin/kafka-topics.sh --delete --topic test-topic --bootstrap-server {% for k in groups['kafka'] %}{% if k != groups['kafka'][0] %},{% endif %}{{ k }}:{{ kafka.bootstrap_port }}{% endfor %}"
      failed_when: False

- name: Uninstall Kafka
  hosts: kafka
  become: no
  vars:
    kafka_home: "{{ bigdata_home }}/kafka"
  tasks:
    - name: Stop Kafka cluster
      command: "{{ kafka_home }}/bin/kafka-server-stop.sh"
      failed_when: False
    - name: Wait
      pause:
        seconds: 5
    - name: Remove directory
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ bigdata_home }}/{{ installer.kafka.replace('.tgz', '') }}"
        - "{{ kafka_home }}"
        - "{{ kafka.log_dir }}"
      failed_when: False
