---

- name: Uninstall pyenv
  hosts: pyenv
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ remote_user }}/.pyenv"
