---

- name: Uninstall Ranger Plugins
  hosts: namenode
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    plugin_home: "{{ bigdata_home }}/ranger_plugin"
  tasks:
    - name: Disable Ranger HDFS Plugin
      become: yes
      shell: "export JAVA_HOME=\"/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-11.el8.x86_64\" && sh {{ hdfs_plugin_home }}/disable-hdfs-plugin.sh"
    - name: Remove directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ plugin_home }}/{{ installer.ranger_hdfs.replace('.tar.gz', '') }}"
        - "{{ plugin_home }}/hdfs"
      failed_when: False

