---

- name: Uninstall UFK
  hosts: ufk
  remote_user: "{{ remote_user }}"
  become: yes
  vars:
    ufk_home: "{{ bigdata_home }}/ufk"
  tasks:
    - name: Stop UFK server
      command: "/usr/bin/docker compose -f {{ ufk_home }}/docker-compose.yml down"
      failed_when: false
    - name: Remove directory
        file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "{{ bigdata_home }}/kafka-ui-0.5.1"
          - "{{ ufk_home }}"
        failed_when: False