- name: Uninstall MariaDB
  hosts: mariadb
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Stop MariaDB server
      command: "{{ mariadb.home_dir }}/bin/mysqladmin shutdown --socket={{ mariadb.home_dir }}/mysql.sock "
      failed_when: False
    - name: Remove directory
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ mariadb.home_dir }}"
        - "{{ mariadb.data_dir }}"
        - "{{ mariadb.home_dir.replace('/mariadb','') }}/{{ installer.mariadb.replace('.tar.gz', '') }}"
