############################################
# 2022-12-09
# 데이터운영팀
# Bigdata Cluster 구축용 Ansible 설정 파일
#
# 개인 테스트용
############################################

# OS 사용자명
remote_user: "igkim"

# Java Home 디렉토리
java_home: "/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.352.b08-2.el8_7.x86_64"

# 기본 홈 디렉토리
bigdata_home: "/opt/bigdata"

# 설치파일 디렉토리
installer_home: "/home/igkim/install"

# 서비스별 설치파일
installer: 
  zookeeper: "apache-zookeeper-3.6.3-bin.tar.gz"
  hadoop: "hadoop-3.3.4.tar.gz"
  kafka: "kafka_2.13-3.3.1.tgz"

# Zookeeper 설정
zookeeper: 
  client_port: 12181
  data_dir: "/opt/bigdata/zookeeper/data"
  # 내부 통신용 포트
  internal_follower_port: 12888
  internal_leader_port: 13888

# Hadoop 설정
hadoop:
  hdfs:
    # Namenode HA Endpoint
    nameservice: "igkim-hdfs"
    # Namenode 설정
    namenode_dir: "/data/nn"
    namenode_rpc_port: 8020
    namenode_http_port: 50070
    # Datanode 설정
    datanode_dir: "/data/dn"
    # Journalnode 설정
    journalnode_dir: "/data/jn"
    journalnode_shared_edits_port: 8485
    # HDFS 설정
    replication_factor: 3
    block_size: 134217728
    webhdfs_enabled: true
    permission_umask: "022"
    trash_interval: 1
  yarn:
    # Resourcemanager HA Endpoint
    cluster_id: "igkim-yarn"
    # Resourcemanager 설정
    resourcemanager_scheduler_port: 8030
    resourcemanager_resource_tracker_port: 8031
    resourcemanager_port: 8032
    resourcemanager_admin_port: 8033
    resourcemanager_webapp_port: 8088
    resourcemanager_webapp_https_port: 8090
    # Mapreduce에서 사용할 Framework (e.g. yarn, classic, local)
    mapreduce_framework: "yarn"

    jobhistoryserver_port: 10020
    jobhistoryserver_http_port: 19888
    jobhistoryserver_https_port: 19890
    jobhistoryserver_admin_port: 10033

# Kafka 설정
kafka:
  log_dir: "/data/kafka"
  num_partition: 1
  bootstrap_port: 19092
  controller_port: 19093