### 2023.08.16
# FQDN으로 작성, Alias 사용 금지

bigdata:
  hosts:
    # Cluster all hosts
    server-1:
      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
    server-2:
    server-3:

  children:

    ## Worker Node
    #  (DataNode, NodeManager, RegionServer, Spark, NodeExporter가 설치될 Node)
    worker:
      hosts:
        server-[1:3]:

    ## Scale-in (Decommission할 Worker Node, worker 목록에서 삭제 필수)
    scale-in:
      hosts:


    ## ZooKeeper Cluster
    zookeeper:
      hosts:
        server-1:
          myid: 1
        server-2:
          myid: 2
        server-3:
          myid: 3

    ## Hadoop Cluster
    hadoop:
      hosts:
        server-[1:3]:
      children:
        namenode:
          hosts:
            server-[1:2]:
        # Use worker instead of datanode.
        datanode:
        journalnode:
          hosts:
            server-[1:3]:
        resourcemanager:
          hosts:
            server-[2:3]:
        # Use worker instead of nodemanager.
        nodemanager:
        jobhistoryserver:
          hosts:
            server-1:
        httpfs:
          hosts:
            server-1:

    ## Kafka Cluster
    kafka:
      hosts:
        server-1:
          nodeid: 1
        server-2:
          nodeid: 2
        server-3:
          nodeid: 3

    ## pyenv
    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        server-[2:3]:

    ## MariaDB Server
    # pyenv 설치 필요
    mariadb:
      hosts:
        server-3:
#          ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

    ## MySQL Server
    # pyenv 설치 필요
    mysql:
      hosts:
        server-3:

    ## Hive Server
    # MariaDB 설치 필요
    hive:
      children:
        hive-server2:
          hosts:
            server-[2:3]:
        metastore:
          hosts:
            server-[2:3]:

    ## Spark
    # Use worker instead of spark.
    spark:
      children:
        spark-history:
          hosts:
            server-3:

    ## HBase Cluster
    hbase:
      hosts:
      children:
        hbase-master:
          hosts:
            server-[1:2]:
        # Use worker instead of region-server.
        region-server:

    ## Hue Server
    hue:
      hosts:
        server-3:

    ## Sqoop client
    sqoop:
      hosts:
        server-3:

    ## UI for Apache Kafka Web Server
    ufk:
      hosts:
        server-3:

    ## Airflow
    airflow:
      hosts:
        server-[1:3]:
      children:
        airflow-webserver:
          hosts:
            server-3:
        airflow-scheduler:
          hosts:
            server-[2:3]:
        airflow-celery-flower:
          hosts:
            server-3:
        airflow-celery-worker:
          hosts:
            server-[1:3]:

    ## Zeppelin
    zeppelin:
      hosts:
        server-3:

    ## Redis Sentinel Cluster (3대로 구성)
    redis:
      hosts:
        server-[1:3]:

    R:
      hosts:
        server-3:

    prometheus:
      hosts:
        server-3:

    # Use all hosts.
    node-exporter:

    blackbox-exporter:
      hosts:
        server-3:

    check-process-exporter:
      hosts:
        server-[1:3]:

    kminion-exporter:
      hosts:
        server-3:

    grafana:
      hosts:
        server-3:

    ranger:
      hosts:
        server-3: