############################################
# 2023-09-05
# Bigdata Cluster 구축용 Host 설정 파일
#
# Cloud 장비용
############################################

### 2023.08.16
# FQDN으로 작성, Alias 사용 금지

bigdata:
  hosts:
    # Cluster all hosts
    server-1.novalocal:
      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
    server-2.novalocal:
      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
    server-3.novalocal:
      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

  children:

    ## Worker Node (노드 추가시 이 목록에 추가)
    #  (DataNode, NodeManager, RegionServer, Spark가 설치될 Node)
    worker:
      hosts:
        server-[1:3].novalocal:

    ## Scale-in (노드 제거)
    # (제거할 Worker Node는 worker 목록에서 삭제 필수)
    scale-in:
      hosts:


    ## ZooKeeper Cluster
    zookeeper:
      hosts:
        server-1.novalocal:
          myid: 1
        server-2.novalocal:
          myid: 2
        server-3.novalocal:
          myid: 3

    ## Hadoop Cluster
    hadoop:
      hosts:
        server-[1:3].novalocal:
      children:
        namenode:
          hosts:
            server-[1:2].novalocal:
        # Use worker instead of datanode.
        datanode:
        journalnode:
          hosts:
            server-[1:3].novalocal:
        resourcemanager:
          hosts:
            server-[2:3].novalocal:
        # Use worker instead of nodemanager.
        nodemanager:
        jobhistoryserver:
          hosts:
            server-1.novalocal:
        httpfs:
          hosts:
            server-1.novalocal:

    ## Kafka Cluster
    kafka:
      hosts:
        server-1.novalocal:
          nodeid: 1
        server-2.novalocal:
          nodeid: 2
        server-3.novalocal:
          nodeid: 3

    ## pyenv
    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        server-[2:3].novalocal:

    ## MariaDB Server
    # pyenv 설치 필요
    mariadb:
      hosts:
        server-3.novalocal:
#          ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

    ## MySQL Server
    # pyenv 설치 필요
    mysql:
      hosts:
        server-3.novalocal:

    ## Hive Server
    # MariaDB 설치 필요
    hive:
      children:
        hive-server2:
          hosts:
            server-[2:3].novalocal:
        metastore:
          hosts:
            server-[2:3].novalocal:

    ## Spark
    # Use worker instead of spark.
    spark:
      children:
        spark-history:
          hosts:
            server-3.novalocal:

    ## HBase Cluster
    hbase:
      hosts:
      children:
        hbase-master:
          hosts:
            server-[1:2].novalocal:
        # Use worker instead of region-server.
        region-server:

    ## Hue Server
    hue:
      hosts:
        server-3.novalocal:

    ## Sqoop client
    sqoop:
      hosts:
        server-3.novalocal:

    ## UI for Apache Kafka Web Server
    ufk:
      hosts:
        server-3.novalocal:

    ## Airflow
    airflow:
      hosts:
        server-[1:3].novalocal:
      children:
        airflow-webserver:
          hosts:
            server-3.novalocal:
        airflow-scheduler:
          hosts:
            server-[2:3].novalocal:
        airflow-celery-flower:
          hosts:
            server-3.novalocal:
        airflow-celery-worker:
          hosts:
            server-[1:3].novalocal:

    ## Zeppelin
    zeppelin:
      hosts:
        server-3.novalocal:

    ## Redis Sentinel Cluster (3대로 구성)
    redis:
      hosts:
        server-[1:3].novalocal:

    R:
      hosts:
        server-3.novalocal:

    prometheus:
      hosts:
        server-3.novalocal:

    # Use all hosts.
    node-exporter:

    blackbox-exporter:
      hosts:
        server-3.novalocal:

    check-process-exporter:
      hosts:
        server-[1:3].novalocal:

    kminion-exporter:
      hosts:
        server-3.novalocal:

    grafana:
      hosts:
        server-3.novalocal:

    ranger:
      hosts:
        server-3.novalocal: