---

- name: Install Redis
  hosts: redis
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    redis_home: "{{ bigdata_home }}/redis"
  tasks:
    - name: Edit Redis configuration
      lineinfile:
        path: "{{ redis_home }}/conf/redis.conf"
        regexp: "{{ item.key }}"
        line: "{{ item.value }}"
      with_dict:
        - "^bind 127.0.0.1 -::1$": "bind 0.0.0.0"
        - "^protected-mode yes$": "protected-mode no"
        - "^port*[0-9]$": "port {{ redis.port }}"
        - "^daemonize no$": "daemonize yes"
        - "^pidfile*": "pidfile {{ redis_home }}/redis.pid"
        - "^logfile*": "logfile {{ redis_home }}/logs/redis.log"

- name: Edit Redis Slave configuration
  hosts: "{{ groups['redis'][1] }}, {{ groups['redis'][2] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    redis_home: "{{ bigdata_home }}/redis"
  tasks:
    - name: Edit Redis Slave configuration
      lineinfile:
        path: "{{ redis_home }}/conf/redis.conf"
        regexp: "^replicaof*[0-9]$"
        line: "replicaof {{ groups['redis'][0] }} {{ redis.port }}"
        insertafter: "^# replicaof <masterip> <masterport>"