- name: Edit Spark configuration files
  hosts: spark
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Edit Spark configuration files
      template:
        src: spark/{{ item }}
        dest: "{{ bigdata_home }}/spark/conf/"
        mode: 0644
      with_items:
        - spark-env.sh
        - spark-defaults.conf