- name: Edit UFK configuration files
  hosts: ufk
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    ufk_home: "{{ bigdata_home }}/kafka-ui"
  tasks:
    - name: Edit UFK configuration files
      template:
        src: "ufk/{{ item }}"
        dest: "{{ ufk_home }}/"
        mode: 0644
      with_items:
        - "docker-compose.yml"