- name: Edit UFK configuration files
  hosts: ufk
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Edit UFK configuration files
      template:
        src: "{{ item }}"
        dest: "{{ bigdata_home }}/ufk/"
        mode: 0644
      with_fileglob:
        - "{{ ansible_home }}/playbooks/edit/templates/ufk/docker-compose.yml"