- name: Edit Hive configuration files
  hosts: hive
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Edit Hive configuration files
      template:
        src: "{{ item }}"
        dest: "{{ bigdata_home }}/hive/conf/"
        mode: 0644
      with_fileglob:
        - "{{ ansible_home }}/playbooks/edit/templates/hive/*"
    - name: Test
      lineinfile:
        path: "{{ bigdata_home }}/hive/bin/hive"
        line: |
          for f in ${HADOOP_HOME}/share/hadoop/*/*.jar; do
            CLASSPATH=${CLASSPATH}:$f;
          done

        insertbefore: "# add the auxillary jars such as serdes"
