---

- name: Install Redis
  hosts: redis
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    redis_home: "{{ bigdata_home }}/redis"
  tasks:
    - name: Edit Redis configuration
      lineinfile:
        path: "{{ redis_home }}/conf/redis.conf"
        regexp: "{{ item.key }}"
        line: "{{ item.value }}"
      with_dict:
        - "^port [0-9]{1,5}$": "port {{ redis.port }}"