- name: Edit Hadoop configuration files
  hosts: hadoop, worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hadoop_home: "{{ bigdata_home }}/hadoop"
  tasks:
    - name: Check Ranger-HDFS plugin status
      shell: "cat {{ hadoop_home }}/conf/hdfs-site.xml | grep org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer"
      register: hdfs_stat
      failed_when: false
    - name: Check Ranger-YARN plugin status
      shell: "cat /opt/bigdata/hadoop/conf/yarn-site.xml | grep org.apache.ranger.authorization.yarn.authorizer.RangerYarnAuthorizer"
      register: yarn_stat
      failed_when: false
    - name: Edit Hadoop configuration files
      template:
        src: hadoop/{{ item }}
        dest: "{{ bigdata_home }}/hadoop/conf/"
        mode: 0644
      with_items:
        - "hdfs-site.xml"
        - "core-site.xml"
        - "yarn-site.xml"
        - "mapred-site.xml"
        - "httpfs-site.xml"
    - name: Add Ranger-HDFS plugin configuration
      blockinfile:
        path: "{{ hadoop_home }}/conf/hdfs-site.xml"
        block: |4
                <property>
                    <name>dfs.permissions.enabled</name>
                    <value>true</value>
                </property>
                <property>
                    <name>dfs.permissions</name>
                    <value>true</value>
                </property>
                <property>
                    <name>dfs.namenode.inode.attributes.provider.class</name>
                    <value>org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer</value>
                </property>
                <property>
                    <name>dfs.permissions.ContentSummary.subAccess</name>
                    <value>true</value>
                </property>
        insertbefore: "</configuration>"
      when: '"org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer" in hdfs_stat.stdout'
    - name: Add Ranger-YARN plugin configuration
      blockinfile:
        path: "{{ hadoop_home }}/conf/yarn-site.xml"
        block: |4
                <property>
                    <name>yarn.authorization-provider</name>
                    <value>org.apache.ranger.authorization.yarn.authorizer.RangerYarnAuthorizer</value>
                </property>
        insertbefore: "</configuration>"
      when: '"org.apache.ranger.authorization.yarn.authorizer.RangerYarnAuthorizer" in yarn_stat.stdout'