---

- name: Edit Grafana configurations
  hosts: grafana
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    grafana_home: "{{ bigdata_home }}/grafana"
  tasks:
    - name: Edit Grafana configuration
      lineinfile:
        path: "{{ grafana_home }}/conf/defaults.ini"
        regexp: "^{{ item.key }} = "
        line: "{{ item.key }} = {{ item.value }}"
      with_dict:
        "http_port": "{{ grafana.web_port }}"
        "admin_email": "igkim@daou.co.kr"
## 개발 완료시 적용
#    - name: Add Provisioning dashboard list
#      copy:
#        src: "grafana/dashboard/{{ item }}"
#        dest: "{{ grafana_home }}/conf/provisioning/dashboards/json/"
#        mode: 0640
#      with_items:
#        - "BigdataClusterResourceUsage-1692776398380.json"
    - name: Add Provisioning dashboard list
      copy:
        src: "{{ item }}"
        dest: "{{ grafana_home }}/conf/provisioning/dashboards/json/"
        mode: 0640
      with_items:
        - "{{ ansible_home }}/files/dashboard/*.json"