---

- name: Install Airflow
  hosts: airflow-webserver, airflow-scheduler, airflow-celery-worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    airflow_home: "{{ bigdata_home }}/airflow"
  tasks:
    - name: Edit Airflow configuration
      lineinfile:
        path: "{{ airflow_home }}/airflow.cfg"
        regexp: "{{ item.key | regex_escape() }} ="
        line: "{{ item.key }} = {{ item.value }}"
      with_dict:
        "default_timezone": "Asia/Seoul"
        "executor": "LocalExecutor"
        "load_examples": "False"
        "sql_alchemy_conn": "mysql://{{ airflow.db_user }}:{{ airflow.db_pw }}@{{ groups['mysql'][0] }}:{{ mysql.jdbc_port }}/{{ airflow.db_name }}"
        "celery_logging_level": "INFO"
        "default_ui_timezone": "Asia/Seoul"
        "web_server_port": "{{ airflow.web_port }}"
        "broker_url": "{% for r in groups['redis'] %}{% if r != groups['redis'][0] %};{% endif %}sentinel://{{ r }}:{{ redis.sentinel_port }}{% endfor %}"
        "result_backend": "mysql://{{ airflow.db_user }}:{{ airflow.db_pw }}@{{ groups['mysql'][0] }}:{{ mysql.jdbc_port }}/{{ airflow.db_name }}"
        "dag_dir_list_interval": "{{ airflow.dag_dir_list_interval }}"
        "schedule_after_task_execution": "False"