---

- name: Install Redis
  hosts: redis
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    redis_home: "{{ bigdata_home }}/redis"
  tasks:
    - name: Edit Redis configuration
      lineinfile:
        path: "{{ redis_home }}/conf/redis.conf"
        regexp: "{{ item.key }}"
        line: "{{ item.value }}"
      with_dict:
        - "^bind": "bind {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        - "^protected-mode": "protected-mode no"
        - "^port": "port {{ redis.port }}"
        - "^daemonize": "daemonize yes"
        - "^pidfile*": "pidfile \"{{ redis_home }}/redis.pid\""
        - "^logfile*": "logfile \"{{ redis_home }}/logs/redis.log\""
        - "^masterauth": "masterauth \"{{ redis.requirepass }}\""
        - "^requirepass": "requirepass \"{{ redis.requirepass }}\""

    - name: Edit Redis Sentinel monitor configuration
      lineinfile:
        path: "{{ redis_home }}/conf/sentinel.conf"
        regexp: "{{ item.key }}"
        line: "{{ item.value }}"
      with_dict:
        - "^sentinel auth-pass": "sentinel auth-pass mymaster {{ redis.requirepass }}"
        - "^requirepass": "requirepass \"{{ redis.requirepass }}\""
        - "^sentinel down-after-milliseconds": "sentinel down-after-milliseconds mymaster {{ redis.sentinel_down_after_ms }}"
        - "^sentinel resolve-hostnames": "sentinel resolve-hostnames {{ redis.sentinel_resolve_hostname }}"
        - "^sentinel announce-hostnames": "sentinel announce-hostnames {{ redis.sentinel_announce_hostname }}"