- name: Edit Hadoop configuration files
  hosts: hadoop, worker
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hadoop_home: "{{ bigdata_home }}/hadoop"
  tasks:
    - name: Edit Hadoop configuration files
      template:
        src: hadoop/{{ item }}
        dest: "{{ bigdata_home }}/hadoop/conf/"
        mode: 0644
      with_items:
        - "hdfs-site.xml"
        - "core-site.xml"
        - "yarn-site.xml"
        - "mapred-site.xml"
        - "httpfs-site.xml"
    - name: Check Ranger plugin status
      shell: "ls -l {{ hadoop_home }}/conf/ | grep ranger-security.xml"
      register: rp_stat
      failed_when: false
    - name: Debugging
      debug:
        var: rp_stat
    - name: Add Ranger plugin configuration
      blockinfile:
        path: "{{ hadoop_home }}/conf/hdfs-site.xml"
        block: |2
          <property>
              <name>dfs.permissions.enabled</name>
              <value>true</value>
          </property>
          <property>
              <name>dfs.permissions</name>
              <value>true</value>
          </property>
          <property>
              <name>dfs.namenode.inode.attributes.provider.class</name>
              <value>org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer</value>
          </property>
          <property>
              <name>dfs.permissions.ContentSummary.subAccess</name>
              <value>true</value>
          </property>
        ins before: "</configuration>"
      when: '"ranger-security.xml" in rp_stat.stdout'