- name: Edit Prometheus configuration
  hosts: prometheus
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    prometheus_home: "{{ bigdata_home }}/prometheus"
  tasks:
    - name: Edit Prometheus configuration
      template:
        src: "prometheus/{{ item }}"
        dest: "{{ prometheus_home }}/conf/"
        mode: 0644
      with_items:
        - "prometheus.yml"