- name: Edit HBase configuration files
  hosts: hbase, worker
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Edit HBase configuration files
      template:
        src: "hbase/{{ item }}"
        dest: "{{ bigdata_home }}/hbase/conf/"
        mode: 0644
      with_items:
        - "backup-masters"
        - "hbase-env.sh"
        - "hbase-site.xml"
        - "regionservers"