---

- name: Edit Grafana configurations
  hosts: grafana
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    grafana_home: "{{ bigdata_home }}/grafana"
  tasks:
    - name: Edit Grafana configuration
      lineinfile:
        path: "{{ grafana_home }}/conf/defaults.ini"
        regexp: "^{{ item.key }} = "
        line: "{{ item.key }} = {{ item.value }}"
      with_dict:
        "http_port": "{{ grafana.web_port }}"
        "admin_email": "igkim@daou.co.kr"