---

- name: HBase Master Rolling restart
  hosts: "{{ groups['hbase-master'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Check HBase Master pid
      shell: "/usr/bin/jps | grep 'HMaster' | awk '{print $1}'"
      register: hm_pid
      failed_when: false
    - name: Kill HBase Master
      command: "/usr/bin/kill -9 {{ hm_pid.stdout }}"
      when: hm_pid.stdout != ""
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Stop Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh stop master"
      when: '"HMaster" in hm_result'
    - name: Pause
      pause:
        seconds: 15
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Start HBase Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"
      when: '"HMaster" not in hm_result'
    - name: Pause
      pause:
        minutes: 1

- name: HBase Master-backup Rolling restart
  hosts: "{{ groups['hbase-master'][1] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Check HBase Master pid
      shell: "/usr/bin/jps | grep 'HMaster' | awk '{print $1}'"
      register: hm_pid
      failed_when: false
    - name: Kill HBase Master
      command: "/usr/bin/kill -9 {{ hm_pid.stdout }}"
      when: hm_pid.stdout != ""
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Stop Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh stop master"
      when: '"HMaster" in hm_result'
    - name: Pause
      pause:
        seconds: 15
    - name: Check HBase Master
      shell: "/usr/bin/jps | grep 'HMaster'"
      register: hm_result
      failed_when: false
    - name: Start HBase Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"
      when: '"HMaster" not in hm_result'