---

- name: HBase Master Rolling restart
  hosts: "{{ groups['hbase-master'][0] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Stop Master
      command: "{{ hbase_home }}/bin/hbase-daemon.sh stop master"
    - name: Check HBase Master pid
      shell: "/usr/bin/jps | grep 'HMaster' | awk '{print $1}'"
      register: hm_pid
      failed_when: false
    - name: Kill HBase Master
      command: "/usr/bin/kill -9 {{ hm_pid.stdout }}"
      when: hm_pid.stdout != ""
    - name: Pause
      pause:
        seconds: 15
    - name: Start
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"
    - name: Pause
      pause:
        minutes: 1

- name: HBase Master Rolling restart
  hosts: "{{ groups['hbase-master'][1] }}"
  remote_user: "{{ remote_user }}"
  become: no
  vars:
    hbase_home: "{{ bigdata_home }}/hbase"
  tasks:
    - name: Stop Master-backup
      command: "{{ hbase_home }}/bin/hbase-daemon.sh stop master"
    - name: Check HBase Master pid
      shell: "/usr/bin/jps | grep 'HMaster' | awk '{print $1}'"
      register: hm_pid
      failed_when: false
    - name: Kill HBase Master
      command: "/usr/bin/kill -9 {{ hm_pid.stdout }}"
      when: hm_pid.stdout != ""
    - name: Pause
      pause:
        seconds: 15
    - name: Start
      command: "{{ hbase_home }}/bin/hbase-daemon.sh start master"