---

- name: Init JAVA_HOME
  hosts: bigdata
  remote_user: "{{ remote_user }}"
  become: no
  tasks:
    - name: Edit JAVA_HOME
      lineinfile:
        path: "/home/{{ remote_user }}/.bashrc"
        regexp: "^export JAVA_HOME="
        line: "export JAVA_HOME=\"{{ java_home }}\""