bigdata:
  hosts:
    igkim-[01:03]:
  children:
    zookeeper:
      hosts:
        igkim-01:
          myid: 1
        igkim-02:
          myid: 2
        igkim-03:
          myid: 3
    hadoop:
      hosts:
        igkim-[01:03]:
      children:
        namenode:
          hosts:
            igkim-[01:02]:
        datanode:
          hosts:
            igkim-[01:03]:
        journalnode:
          hosts:
            igkim-[01:03]:
        resourcemanager:
          hosts:
            igkim-[02:03]:
        nodemanager:
          hosts:
            igkim-[01:03]:
        jobhistoryserver:
          hosts:
            igkim-01:
    kafka:
      hosts:
        igkim-01:
          nodeid: 1
        igkim-02:
          nodeid: 2
        igkim-03:
          nodeid: 3
    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        igkim-03:
    # pyenv 설치 필요
    mariadb:
      hosts:
        igkim-03:
    hive:
      children:
        hive-server:
          hosts:
            igkim-[02:03]:
        metastore:
          hosts:
            igkim-[02:03]:
