############################################
# 2024-09-04
# AI Cluster 구축용 Host 설정 파일
#
# 개발 장비용
############################################

### 2023.08.16
# FQDN으로 작성, Alias 사용 금지

bigdata:
  hosts:
    # Cluster all hosts
    devaidbA01:
#      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
    devgpuA01:
#      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
  children:

    ## pyenv
    # check-process-exporter 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        devaidbA01:
        devgpuA01:

    # Use all hosts.
    node-exporter:
      hosts:
        devaidbA01:
        devgpuA01:

    check-process-exporter:
      hosts:
        devaidbA01:
        devgpuA01:
