bigdata:
  hosts:
    bd-kw-dev[01:03]:
  children:
    zookeeper:
      hosts:
        bd-kw-dev01:
          myid: 1
        bd-kw-dev02:
          myid: 2
        bd-kw-dev03:
          myid: 3
    hadoop:
      hosts:
        bd-kw-dev[01:03]:
      children:
        namenode:
          hosts:
            bd-kw-dev[01:02]:
        datanode:
          hosts:
            bd-kw-dev[01:03]:
        journalnode:
          hosts:
            bd-kw-dev[01:03]:
        resourcemanager:
          hosts:
            bd-kw-dev[02:03]:
          nodemanager:
            hosts:
              bd-kw-dev[01:03]:
          jobhistoryserver:
            hosts:
              bd-kw-dev01:
