bigdata:
  hosts:
    bd-kw-dev[01:03]:
      ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"
  children:

    ## ZooKeeper Cluster
    zookeeper:
      hosts:
        bd-kw-dev01:
          myid: 1
        bd-kw-dev02:
          myid: 2
        bd-kw-dev03:
          myid: 3

    ## Hadoop Cluster
    hadoop:
      hosts:
        bd-kw-dev[01:03]:
      children:
        namenode:
          hosts:
            bd-kw-dev[01:02]:
        datanode:
          hosts:
            bd-kw-dev[01:03]:
        journalnode:
          hosts:
            bd-kw-dev[01:03]:
        resourcemanager:
          hosts:
            bd-kw-dev[02:03]:
        nodemanager:
          hosts:
            bd-kw-dev[01:03]:
        jobhistoryserver:
          hosts:
            bd-kw-dev01:

    ## Kafka Cluster
    kafka:
      hosts:
        bd-kw-dev01:
          nodeid: 1
        bd-kw-dev02:
          nodeid: 2
        bd-kw-dev03:
          nodeid: 3

    ## pyenv
    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        bd-kw-dev[02:03]:

    ## MariaDB Server
    # pyenv 설치 필요
    mariadb:
      hosts:
        bd-kw-dev03:
#          ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

    ## MySQL Server
    # pyenv 설치 필요
    mysql:
      hosts:
        bd-kw-dev03:

    ## Hive Server
    # MariaDB 설치 필요
    hive:
      children:
        hive-server2:
          hosts:
            bd-kw-dev[02:03]:
        metastore:
          hosts:
            bd-kw-dev[02:03]:

    ## Spark
    spark:
      hosts:
        bd-kw-dev[01:03]:
      children:
        spark-history:
          hosts:
            bd-kw-dev03:

    ## HBase Cluster
    hbase:
      hosts:
        bd-kw-dev[01:03]:
      children:
        hbase-master:
          hosts:
            bd-kw-dev[01:02]:
        region-server:
          hosts:
            bd-kw-dev[01:03]:

    ## Hue Server
    hue:
      hosts:
        bd-kw-dev03:

    ## Sqoop client
    sqoop:
      hosts:
        bd-kw-dev[01:03]:

    ## UI for Apache Kafka Web Server
    ufk:
      hosts:
        bd-kw-dev03:

    ## Airflow
    airflow:
      hosts:
        bd-kw-dev[01:03]:
      children:
        airflow-webserver:
          hosts:
            bd-kw-dev03:
        airflow-scheduler:
          hosts:
            bd-kw-dev03:
        airflow-celery-worker:
          hosts:
            bd-kw-dev[01:03]:

    ## Zeppelin
    zeppelin:
      hosts:
        bd-kw-dev03:

    ## Redis Sentinel Cluster (3대로 구성)
    redis:
      hosts:
        bd-kw-dev[01:03]:

    R:
      hosts:
        bd-kw-dev03:

    prometheus:
      hosts:
        bd-kw-dev03: