bigdata:
  hosts:
    bd-kw-dev[01:03]:
  children:
    zookeeper:
      hosts:
        bd-kw-dev01:
          myid: 1
        bd-kw-dev02:
          myid: 2
        bd-kw-dev03:
          myid: 3
    hadoop:
      hosts:
        bd-kw-dev[01:03]:
      children:
        namenode:
          hosts:
            bd-kw-dev[01:02]:
        datanode:
          hosts:
            bd-kw-dev[01:03]:
        journalnode:
          hosts:
            bd-kw-dev[01:03]:
        resourcemanager:
          hosts:
            bd-kw-dev[02:03]:
        nodemanager:
          hosts:
            bd-kw-dev[01:03]:
        jobhistoryserver:
          hosts:
            bd-kw-dev01:
    kafka:
      hosts:
        bd-kw-dev01:
          nodeid: 1
        bd-kw-dev02:
          nodeid: 2
        bd-kw-dev03:
          nodeid: 3

    # Hive metastore로 사용할 MariaDB 설치를 위한 pyenv 선행 설치
    pyenv:
      hosts:
        bd-kw-dev[02:03]:

    # pyenv 설치 필요
    mariadb:
      hosts:
        bd-kw-dev03:
#          ansible_python_interpreter: "/home/{{ remote_user }}/.pyenv/shims/python"

    # MariaDB 설치 필요
    hive:
      children:
        hive-server2:
          hosts:
            bd-kw-dev[02:03]:
        metastore:
          hosts:
            bd-kw-dev[02:03]:

    spark:
      hosts:
        bd-kw-dev[01:03]:
      children:
        spark-history:
          hosts:
            bd-kw-dev03:

    hbase:
      children:
        master:
          hosts:
            bd-kw-dev[01:02]:
        region:
          hosts:
            bd-kw-dev[01:03]: